### ISSUE TITLE
When sending a POST to the Lambda Function URL, it doesn't work.

### ISSUE THREAD

**Issue by watany-dev** [honojs/hono#1075]
If I write the following code in Lambda and try to POST it from FunctionURL, it fails.

```ts
import { Hono } from 'hono'
import { handle } from 'hono/aws-lambda'
import { logger } from 'hono/logger'

const app = new Hono()

interface UserBody {
  user: string;
}

app.use('*', logger())
app.post('/', async (c) => {
  const { user } = await c.req.json<UserBody>();
  if (!user) {
    return c.text('Please Setting "user"', 400)
  } 
  return c.json({"user": user})
})
app.get('/', (c) => { 
    return c.text(`Hono is running on ${c.runtime}\n`)
})
export const handler = handle(app)

```

- error

```json
{
    "errorType": "TypeError",
    "errorMessage": "Request with GET/HEAD method cannot have body.",
    "stack": [
        "TypeError: Request with GET/HEAD method cannot have body.",
        "    at new Request (node:internal/deps/undici/undici:7171:17)",
        "    at createRequest (/var/task/index.js:1570:10)",
        "    at Runtime.handler (/var/task/index.js:1540:17)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1086:29)"
    ]
```

I suspected it might be an issue with the event, so I investigated it. (I couldn't find anything about it in the official documentation.)

```node
export const handler = async(event, context, callback) => {
    return {
        statusCode: 200,
        body: "EVENT: \n" + JSON.stringify(event, null, 2),
    };
};
```

- GET
```bash
curl -X GET -H 'Content-Type: application/json' -d '{ "usr": "uga" }' https://v6omzqz2b2ck4asqa3f6ktm26m0ogpxq.lambda-url.ap-northeast-1.on.aws/
EVENT: 
{
  "version": "2.0",
  "routeKey": "$default",
  "rawPath": "/",
  "rawQueryString": "",
  "headers": {
    "content-length": "16",
    "x-amzn-tls-cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256",
    "x-amzn-tls-version": "TLSv1.2",
    "x-amzn-trace-id": "Root=1-64577867-46dd53e40ce1f6e5279c68bd",
    "x-forwarded-proto": "https",
    "host": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq.lambda-url.ap-northeast-1.on.aws",
    "x-forwarded-port": "443",
    "content-type": "application/json",
    "x-forwarded-for": "35.77.42.73",
    "accept": "*/*",
    "user-agent": "curl/7.88.1"
  },
  "requestContext": {
    "accountId": "anonymous",
    "apiId": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq",
    "domainName": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq.lambda-url.ap-northeast-1.on.aws",
    "domainPrefix": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq",
    "http": {
      "method": "GET",
      "path": "/",
      "protocol": "HTTP/1.1",
      "sourceIp": "35.77.42.73",
      "userAgent": "curl/7.88.1"
    },
    "requestId": "ef5bdbc2-2f20-4769-9939-9a5a712e5be4",
    "routeKey": "$default",
    "stage": "$default",
    "time": "07/May/2023:10:07:35 +0000",
    "timeEpoch": 1683454055510
  },
  "body": "{ \"usr\": \"uga\" }",
  "isBase64Encoded": false
}
```

- POST

```bash
 curl -X POST -H 'Content-Type: application/json' -d '{ "usr": "uga" }' https://v6omzqz2b2ck4asqa3f6ktm26m0ogpxq.lambda-url.ap-northast-1.on.aws/
EVENT: 
{
  "version": "2.0",
  "routeKey": "$default",
  "rawPath": "/",
  "rawQueryString": "",
  "headers": {
    "content-length": "16",
    "x-amzn-tls-cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256",
    "x-amzn-tls-version": "TLSv1.2",
    "x-amzn-trace-id": "Root=1-64577775-7b347e31250dd7241a79d0b0",
    "x-forwarded-proto": "https",
    "host": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq.lambda-url.ap-northeast-1.on.aws",
    "x-forwarded-port": "443",
    "content-type": "application/json",
    "x-forwarded-for": "35.77.42.73",
    "accept": "*/*",
    "user-agent": "curl/7.88.1"
  },
  "requestContext": {
    "accountId": "anonymous",
    "apiId": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq",
    "domainName": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq.lambda-url.ap-northeast-1.on.aws",
    "domainPrefix": "v6omzqz2b2ck4asqa3f6ktm26m0ogpxq",
    "http": {
      "method": "POST",
      "path": "/",
      "protocol": "HTTP/1.1",
      "sourceIp": "35.77.42.73",
      "userAgent": "curl/7.88.1"
    },
    "requestId": "e3114561-02fc-4479-8bfb-34b8b28d6382",
    "routeKey": "$default",
    "stage": "$default",
    "time": "07/May/2023:10:03:33 +0000",
    "timeEpoch": 1683453813329
  },
  "body": "{ \"usr\": \"uga\" }",
  "isBase64Encoded": false
```

**Comment by yusukebe** [comment]
This is closed by #1076. Thanks.
