### ISSUE TITLE
Can't use websocket with middleware: TypeError: Headers are immutable

### ISSUE THREAD

**Issue by alexgleason** [honojs/hono#1102]
`Deno.upgradeWebSocket` returns a response with immutable headers. But middleware wants to mutate them.

Sample code:

```ts
app.use('/*', logger(), cors({ origin: '*', exposeHeaders: ['link'] }));

app.get('/api/v1/streaming', (c) => {
  const { socket, response } = Deno.upgradeWebSocket(c.req.raw);
  socket.addEventListener('message', (e) => console.log(e));
  return response;
});
```

Result:

```
Trace: TypeError: Headers are immutable.
    at Headers.set (ext:deno_fetch/20_headers.js:362:13)
    at https://deno.land/x/hono@v3.0.2/context.ts:104:22
    at Headers.forEach (ext:deno_webidl/00_webidl.js:1122:11)
    at Context.set res (https://deno.land/x/hono@v3.0.2/context.ts:103:25)
    at dispatch (https://deno.land/x/hono@v3.0.2/compose.ts:57:22)
    at https://deno.land/x/hono@v3.0.2/compose.ts:38:33
    at https://deno.land/x/hono@v3.0.2/middleware/cors/index.ts:59:13
    at dispatch (https://deno.land/x/hono@v3.0.2/compose.ts:37:17)
    at https://deno.land/x/hono@v3.0.2/compose.ts:38:33
    at https://deno.land/x/hono@v3.0.2/middleware/logger/index.ts:66:11
    at errorHandler (https://deno.land/x/hono@v3.0.2/hono.ts:54:11)
    at https://deno.land/x/hono@v3.0.2/compose.ts:74:29
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async https://deno.land/x/hono@v3.0.2/middleware/logger/index.ts:66:5
    at async https://deno.land/x/hono@v3.0.2/hono.ts:246:50
    at async Server.#respond (https://deno.land/std@0.177.0/http/server.ts:299:18)
```

**Comment by alexgleason** [comment]
I realized what I'm trying to do is very stupid. Websocket responses don't need CORS headers, so I simply moved it above the middleware.
