### ISSUE TITLE
Hono 3.0.0 and superior seems not compatible with the cloudflare html rewritters feature

### ISSUE THREAD

**Issue by Stuntback46** [honojs/hono#1125]
Hello,
We were doing that in our middleware:
```
      ctx.res = new HTMLRewriter()
        .on('[data-i18n-key]', new ElementHandler()
        .transform(ctx.res);
```

Now it gives that error:
Trace: TypeError: immutable
    at Headers.delete (/root/git_repo/test/bluewindow-athena/node_modules/undici/lib/fetch/headers.js:280:13)
    at Context.set res [as res] (/root/git_repo/test/bluewindow-athena/node_modules/hono/dist/context.js:193:25)
    at /root/git_repo/test/bluewindow-athena/node_modules/hono/dist/compose.js:58:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at errorHandler (/root/git_repo/test/bluewindow-athena/node_modules/hono/dist/hono-base.js:18:11)
    at /root/git_repo/test/bluewindow-athena/node_modules/hono/dist/compose.js:58:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

If we change to (what we want to avoid to do because we chain the rewritters in fct of the middleware):
```
const res = fetch(ctx.req.raw);
return new HTMLRewriter()
        .on('[data-i18n-key]', new ElementHandler()
        .transform(res);
```

That does not break but the rewritters are not executed (basic example from the documentation: [doc](https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/#handlers)).
Would you consider checking this please?

**Comment by yusukebe** [comment]
Hi @Stuntback46 

This works well:

```ts
import { Hono } from 'hono'
import { html } from 'hono/html'

const app = new Hono()

app.get('/', async (c, next) => {
  await next()
  class AttributeRewriter {
    private attributeName: string
    constructor(attributeName: string) {
      this.attributeName = attributeName
    }
    async element(element: Element) {
      const attribute = element.getAttribute(this.attributeName)
      if (attribute) {
        element.setAttribute(this.attributeName, 'foo')
      }
    }
  }

  const rewriter = new HTMLRewriter().on('img', new AttributeRewriter('src'))
  c.res = rewriter.transform(c.res)
})

app.get('/', (c) => {
  return c.html(
    html`<html>
      <body>
        <img src="/static/images/hono-title.png" width="300" />
      </body>
    </html>`
  )
})

export default app
```

Please try that, referring to it.

**Comment by Stuntback46** [comment]
Thanks @yusukebe to have taken the time for answering
If I replace on your example:
```
app.get('/', (c) => {
  return c.html(
    html`<html>
      <body>
        <img src="/static/images/hono-title.png" width="300" />
      </body>
    </html>`
  )
})
```

by 

```
app.get('/', (c) => {
  return fetch(c.req.raw)
})
```

it breaks with the following error:
```
Trace: TypeError: immutable
    at Headers.delete (/root/.nvm/versions/node/v16.15.0/lib/node_modules/miniflare/node_modules/undici/lib/fetch/headers.js:276:13)
    at Context.set res [as res] (/root/git_repo/test/bluewindow-athena/node_modules/hono/dist/context.js:193:25)
    at /root/git_repo/test/bluewindow-athena/node_modules/hono/dist/compose.js:58:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Hono2.errorHandler (/root/git_repo/test/bluewindow-athena/node_modules/hono/dist/hono-base.js:18:11)
    at Hono2.handleError (/root/git_repo/test/bluewindow-athena/node_modules/hono/dist/hono-base.js:176:19)
    at /root/git_repo/test/bluewindow-athena/node_modules/hono/dist/hono-base.js:240:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EventTarget.[kDispatchFetch] (/root/.nvm/versions/node/v16.15.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/standards/event.ts:385:13)
    at Fetcher.fetch (/root/.nvm/versions/node/v16.15.0/lib/node_modules/miniflare/node_modules/@miniflare/core/src/plugins/bindings.ts:130:17)
```

**Comment by yusukebe** [comment]
If you want to modify it, you need to create a new Response object.

```ts
app.get('/', async (c) => {
  const res = await fetch(c.req.raw)
  return new Response(res.body, res)
})
```

**Comment by yusukebe** [comment]
@Stuntback46 

Great. Is this issue closed?

**Comment by Stuntback46** [comment]
Yes than you very much
