### ISSUE TITLE
Multiline error messages doesn't work on deno

### ISSUE THREAD

**Issue by cah4a** [honojs/hono#1147]
Precondition:
```ts
app.get('/', () => {
   throw new HTTPException(400, `
    I want big messages here,
    so I could print more info about the error
   `);
})
```

Hono version: **v3.2.3**
Deno version: **1.34.0**
Os: MacOs
Expected result: **Response status code 400 with the corresponding text in body**
Actual result: **Response status code 500 with the `Internal Server Error` in body**

Also, I see an error in the log:
```
TypeError: Status text is not valid.
    at initializeAResponse (ext:deno_fetch/23_response.js:184:11)
    at new Response (ext:deno_fetch/23_response.js:322:5)
    at HTTPException.getResponse (https://deno.land/x/hono@v3.2.3/http-exception.ts:20:12)
    at Hono.errorHandler (https://deno.land/x/hono@v3.2.3/hono-base.ts:50:16)
    at Hono.handleError (https://deno.land/x/hono@v3.2.3/hono-base.ts:252:19)
    at https://deno.land/x/hono@v3.2.3/hono-base.ts:309:23
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async Server.#respond (https://deno.land/std@0.190.0/http/server.ts:299:18)
```

**Comment by cah4a** [comment]
That is a workaround:

```ts
class BadRequest extends HTTPException {
    constructor(message: string) {
        super(400, {message});
    }

    getResponse(): Response {
        return new Response(this.message, {status: 400})
    }
}
```

I believe it's not so useful to pass error message both to the body and [statusText](https://github.com/honojs/hono/blob/main/src/http-exception.ts#L22).

**Comment by yusukebe** [comment]
Hi @cah4a 

How about this?

```ts
app.get('/', () => {
  throw new HTTPException(400, {
    res: new Response(
      `I want big messages here,
    so I could print more info about the error
   `,
      {
        status: 400,
      }
    ),
  })
})
```

**Comment by cah4a** [comment]
@yusukebe, that will work.

There are 3 reasons why I'd suggest removing [L22](https://github.com/honojs/hono/blob/main/src/http-exception.ts#L22) completely:

1) Writing `throw new HTTPException(code, message)` is more developer friendly.

2) The reason phrase is an optional part of the HTTP spec and could be stripped by proxies, so the best practice is not relying on it. HTTP/2 just [doesn't have it](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.4).

3) Code that works in a dev environment could break in production: you send one-liners from db for testing purposes, a production version has multiline. That behavior even doesn't mention in the documentation.

What do you think?

**Comment by yusukebe** [comment]
Hi @cah4a,

After considering what you've said, I've come to the conclusion that you're right. It's okay for us to remove it, and in fact, we should. This change will simplify Hono.

Could you create a PR to resolve this?
