### ISSUE TITLE
 React hooks not working inside TSX/JSX file.

### ISSUE THREAD

**Issue by appliquant** [honojs/hono#1186]
(I also posted this issue on [bun.sh repo](https://github.com/oven-sh/bun/issues/3346).

### What version of Bun is running?

0.6.10

### What platform is your computer?

Linux 6.2.6-76060206-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Init project
``` sh
bun create hono hono-app           # Init app
cd hono-app                        # Go to dir
bun add react react-dom @types/react hono     # Install react packages and update hono
```

2. Delete `src/index.ts` and add `src/index.tsx`

```tsx
// index.tsx

import { Hono } from "hono";
import { serveStatic } from "hono/bun";

import LoginPage from "./LoginPage";

const port = process.env.PORT ?? 8000;
const app = new Hono();

app.get("/login", (c) => {
  return c.html(<LoginPage />);
});

console.log(`Server on http://localhost:${port}`);

export default {
  port,
  fetch: app.fetch,
};
```

3. Create Login component `src/LoginView.tsx`

```tsx
// LoginPage.tsx

import { useState } from "react";

const LoginPage = () => {
  const [id, setId] = useState(1); // <------- Error right here
  return (
      <div>
        <h1>LoginView</h1>
      </div>
  );
};

export default LoginPage;

```

4. Update `tsconfig.json`
```json
{
  "compilerOptions": {
    // React (JSX)
    "jsx": "react-jsx",
    "jsxFactory": "jsx",
    "jsxFragmentFactory": "Fragment",
    "jsxImportSource": "hono/jsx",

    "lib": ["ESNext"],
    "module": "esnext",
    "target": "ESNext",
    "moduleResolution": "node",
    "strict": true,
    "skipLibCheck": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,

    // "bun-types" is the important part
    "types": ["bun-types"]
  }
}

```

5. Run `bun run src/index.tsx`

6. Navigate to page `localhost:<port>/login`

7. Expect an error now!

### What is the expected behavior?

To see a rendered page.

### What do you see instead?

An error (Internal Server Error).
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
1617 | 
1618 |   return dispatcher.useContext(Context);
1619 | }
1620 | function useState(initialState) {
1621 |   var dispatcher = resolveDispatcher();
1622 |   return dispatcher.useState(initialState);
             ^
TypeError: null is not an object (evaluating 'dispatcher.useState')
      at useState (/home/user/desktop/dev/bun/hono-app/node_modules/react/cjs/react.development.js:1622:9)
      at /home/user/desktop/dev/bun/hono-app/src/LoginPage.tsx:6:22
      at toStringToBuffer (/home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/middleware/jsx/index.js:123:16)
      at toString (/home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/middleware/jsx/index.js:72:4)
      at /home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/context.js:66:15
      at dispatch (/user/desktop/Bureau/dev/bun/hono-app/node_modules/hono/dist/hono-base.js:200:14)

      at /home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/hono-base.js:18:2
```

### Additional information

Commenting `const [id, setId] = useState(1);` in `LoginPage.tsx` removes the error. Using other hooks such as `useEffect` gives the same error.

**Comment by yudai-nkt** [comment]
I don't know how Bun desugars JSX, but it's likely that Bun refers to `tsconfig.json`'s compiler option. In that case, you need to [configure the compiler option accordingly](https://www.typescriptlang.org/tsconfig#jsx) because templates used by `create-hono-app` is tailored for Hono's JSX.

Fortunately, TypeScript's default is optimized for use cases with React, so you only need to configure the `jsx` option:
```jsonc
{
  "compilerOptions": {
    "jsx": "react-jsx",
    // other options you need
  }
}
```

With the above `tsconfig.json`, the following app works with Wrangler on Node.js (I'm afraid I don't use Bun):

```tsx
import { Hono } from "hono";
import { useState } from "react";
import { renderToString } from "react-dom/server";

const app = new Hono();

const Counter = () => {
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>Current value: {count}</p>
      <button onClick={() => setCount((prev) => prev + 1)}>Click</button>
    </div>
  );
};

app.get("/", (c) => {
  return c.html(renderToString(<Counter />));
});

export default app;
```

Also, please keep in mind that the above code runs on server, so there are no client-side interactivities. You need to prepare hydration.
