### ISSUE TITLE
Does /a fall under the condition of /a/*?

### ISSUE THREAD

**Issue by watany-dev** [honojs/hono#1302]
In the case of the code below, /a/* and /a seem to be evaluated in the same way. I'm not sure if this is an issue specific to Lambda@edge or a fundamental problem.

- index.ts

```ts
import type {
  Callback,
  CloudFrontRequest,
  CloudFrontEdgeEvent,
} from "hono/lambda-edge";

import { Hono } from "hono";
import { handle } from "hono/lambda-edge";
import { logger } from 'hono/logger'

type Bindings = {
  callback: Callback;
  request: CloudFrontRequest;
};

const app = new Hono<{ Bindings: Bindings}>();
app.use('*', logger())

app.all("/a/", async (c, next) => {
  await next()  
  c.env.request.uri = c.env.request.uri + "index.html";
  c.env.callback(null, c.env.request);
});

app.all("/a/*", async (c, next) => {
  await next()  
  c.env.callback(null, c.env.request);
});

export const handler = handle(app);

```

- index.test.ts

```ts
import type {
  Callback,
  CloudFrontRequest,
  CloudFrontEdgeEvent,
} from "hono/lambda-edge";
import { handle } from "hono/lambda-edge";
import { Hono } from "hono";
import { handler } from "./index";

type Bindings = {
  callback: Callback;
  request: CloudFrontRequest;
};

describe("Lambda@Edge Adapter for Hono", () => {

const testCases = [
  { uri: "/a", expectUri: undefined },
  { uri: "/a/", expectUri: "/a/index.html" },
];

  testCases.forEach(({ uri, expectUri }) => {
    it(`should respond correctly for path: ${uri}`, async () => {
      const event = createCloudFrontEvent(uri);
      let result;

      await handler(event, {}, (_err, res) => {
        result = res;
      });

      expect(result?.uri).toBe(expectUri);
    });
  });
});

function createCloudFrontEvent(uri: string): CloudFrontEdgeEvent {
  return {
    Records: [
      {
        cf: {
          config: {
            distributionDomainName: "example.com",
            distributionId: "EDFDVBD6EXAMPLE",
            eventType: "viewer-response",
            requestId:
              "4TyzHTaYWb1GX1qTfsHhEqV6HUDd_BzoBZnwfnvQc_1oF26ClkoUSEQ==",
          },
          request: {
            clientIp: "203.0.113.178",
            headers: {
              host: [
                {
                  key: "Host",
                  value: "example.com",
                },
              ],
            },
            method: "GET",
            querystring: "",
            uri,
          },
        },
      },
    ],
  };
}
```

```bash
 ● Lambda@Edge Adapter for Hono › should respond correctly for path: /a

    expect(received).toBe(expected) // Object.is equality

    Expected: undefined
    Received: "/a"

      47 |       });
      48 |
    > 49 |       expect(result?.uri).toBe(expectUri);
         |                           ^
      50 |     });
      51 |   });
      52 | });

      at src/index.test.ts:49:27
      at fulfilled (src/index.test.ts:5:58)
```

**Comment by yusukebe** [comment]
Hi @watany-dev!

This behavior is not specific to Lambda@Edge; it's the expected behavior in Hono, and not a bug.

If you have routing set up as follows:

```ts
// middleware
app.use('/foo/*', async (c, next) => {
  await next()
})

app.get('/foo', (c) => c.text('foo!'))
```

Then, accessing `GET /foo` will also match the middleware in Hono's router.

In your case, you can alter the behavior by using `c.req.path`, although it may not be the elegant solution.
