### ISSUE TITLE
Server stops if client interrupts during c.stream response

### ISSUE THREAD

**Issue by watany-dev** [honojs/hono#1480]
### What version of Hono are you using?

v3.7.0-rc.1

### What runtime/platform is your app running on?

nodejs

### What steps can reproduce the bug?

The following error occurs when disconnecting on the client side

```bash
npm run start

> start
> tsx src/index.ts

Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.onclose (node:internal/streams/end-of-stream:154:30)
    at ServerResponse.emit (node:events:526:35)
    at ServerResponse.emit (node:domain:489:12)
    at emitCloseNT (node:_http_server:996:10)
    at Socket.onServerResponseClose (node:_http_server:278:5)
    at Socket.emit (node:events:526:35)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:323:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_STATE]: Invalid state: WritableStream is closed
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at writableStreamClose (node:internal/webstreams/writablestream:696:7)
    at writableStreamDefaultWriterClose (node:internal/webstreams/writablestream:1076:10)
    at WritableStreamDefaultWriter.close (node:internal/webstreams/writablestream:472:12)
    at StreamingApi.close (/home/ubuntu/environment/my-app/node_modules/hono/dist/cjs/utils/stream.js:45:23)
    at <anonymous> (/home/ubuntu/environment/my-app/node_modules/hono/dist/cjs/context.js:182:39)
    at <anonymous> {
  code: 'ERR_INVALID_STATE'
}
```

### Additional information

ChatGPT has asked about the following issues. Reference.

```text
1. Add a property to the StreamingApi class to track if the stream is closed.
2. In the write and writeln methods, skip writing if the stream is closed.
3. In the stream method, call stream.close() when the execution of cb(stream) completes (or if an error occurs).
```

```ts
export class StreamingApi {
  private writer: WritableStreamDefaultWriter<Uint8Array>;
  private encoder: TextEncoder;
  private writable: WritableStream;
  private closed: boolean = false; // Added: Track whether the stream is closed

  constructor(writable: WritableStream) {
    this.writable = writable;
    this.writer = writable.getWriter();
    this.encoder = new TextEncoder();
  }

  async write(input: Uint8Array | string) {
    if (this.closed) return; // Added: Skip writing if the stream is closed
    if (typeof input === 'string') {
      input = this.encoder.encode(input);
    }
    await this.writer.write(input);
    return this;
  }

  async writeln(input: string) {
    if (this.closed) return; // Added: Skip writing if the stream is closed
    await this.write(input + '\n');
    return this;
  }

  close() {
    this.closed = true; // Added: Close the stream
    this.writer.close();
  }

  // ... (streamText and stream methods remain the same)

  stream = (
    cb: (stream: StreamingApi) => Promise<void>,
    arg?: StatusCode | ResponseInit,
    headers?: HeaderRecord
  ): Response => {
    const { readable, writable } = new TransformStream();
    const stream = new StreamingApi(writable);
    cb(stream).catch((err) => {
      console.error('Stream error:', err);
    }).finally(() => {
      stream.close(); // Added: Close the stream once cb execution is complete
    });

    // ... (rest of the code remains the same)
  };
}

```

**Comment by yusukebe** [comment]
HI @watany-dev 

This is a Node.js Adapter's bug which is raised in this issue:

https://github.com/honojs/hono/issues/1253

It will be fixed soon. Thanks!

**Comment by yusukebe** [comment]
Hi @tangye1234 , thank you for the comment.

Your implementation looks good at first glance, but when I add the following code I get an `ERR_STREAM_PREMATURE_CLOSE` error.

```ts
this.writer.closed.finally(() => {
  this.closed = true
})
```

I am sure there is room for improvement, but for this PR #1482 I simply used try/catch and ignored the error. I think this is fine, but if there are any serious issues please let me know.

**Comment by yusukebe** [comment]
@watany-dev 

This issue may be fixed in the latest version. Can we close it?

**Comment by watany-dev** [comment]
Yes, I tried it as soon as I could and it worked fine.
