### ISSUE TITLE
crypto is not defined，when i use vitest

### ISSUE THREAD

**Issue by sia-fl** [honojs/hono#1516]
### What version of Hono are you using?

3.7.2

### What runtime/platform is your app running on?

nodejs

### What steps can reproduce the bug?

it's a simple case

```typescript
export const buildToken = async (data: any, exp: number = expDefault) => {
  const now = Date.now();
  const nowWithoutMilliseconds = Math.floor(now / 1000);
  return await sign(
    {
      exp: nowWithoutMilliseconds + exp,
      data,
    },
    keys().jwt,
  );
};
```

when i use vitest
```typescript
it("build token", async () => {
  const token = await buildToken({
    id: 1,
    phone: "19977775555",
  });
  expect(typeof token).toBe("string");
});
```

### What is the expected behavior?

working

### What do you see instead?

i got exception `crypto is not defined`

stacks:

```

ReferenceError: crypto is not defined
    at signing (file:///D:/code/node/mono-container/node_modules/hono/dist/utils/jwt/jwt.js:44:3)
    at Module.sign (file:///D:/code/node/mono-container/node_modules/hono/dist/utils/jwt/jwt.js:61:31)
    at Module.buildToken (D:\code\node\mono-container\src\utils\func.ts:35:16)
    at D:\code\node\mono-container\src\utils\token.spec.ts:7:19
    at file:///D:/code/node/mono-container/node_modules/@vitest/runner/dist/index.js:120:14
    at file:///D:/code/node/mono-container/node_modules/@vitest/runner/dist/index.js:58:26
    at file:///D:/code/node/mono-container/node_modules/@vitest/runner/dist/index.js:546:59
    at Array.map (<anonymous>)
    at callSuiteHook (file:///D:/code/node/mono-container/node_modules/@vitest/runner/dist/index.js:546:47)
    at runTest (file:///D:/code/node/mono-container/node_modules/@vitest/runner/dist/index.js:620:30)

```

### Additional information

add `import crypto from "crypto";` to `node_modules/hono/dist/utils/jwt/jwt.js`

**Comment by yusukebe** [comment]
@sia-fl 

It's not a bug of Hono. It's vitest matter. You may fix it in the following way.

Create a setup file:

```ts
// setup-crypto.js
import * as crypto from 'node:crypto'
global.crypto = crypto
```

and load this in the vitest config:

```ts
import { defineConfig } from 'vite'

export default defineConfig({
  test: {
    setupFiles: ['./setup-crypto.js']
  }
  //...
})
```

**Comment by sia-fl** [comment]
wow，it work
