### ISSUE TITLE
TypeError: Response body object should not be disturbed or locked

### ISSUE THREAD

**Issue by RobertSasak** [honojs/hono#1695]
### What version of Hono are you using?

3.9.0

### What runtime/platform is your app running on?

Firebase functions

### What steps can reproduce the bug?

Here is a simple example with POST end point. 

```ts
import { getRequestListener } from '@hono/node-server'
import { Hono } from 'hono'

const app = new Hono()

app.post('/hello', async (c) => {
  return c.text('Hello World!')
})

export const web = onRequest(getRequestListener(app.fetch))
```

### What is the expected behavior?

Requst should reach Heno and Hello World should appear.

### What do you see instead?

There is an following silent error 500 when doing a POST request with payload. By placing an console.log in https://github.com/honojs/node-server/blob/3575d60a15e345700b81e22376825e98b0a69ebe/src/listener.ts#L42 it is possible to see this error.
```
TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:6433:17)
    at new Request (node:internal/deps/undici/undici:7314:48)
    at /<path>/functions/node_modules/@hono/node-server/dist/listener.js:48:33
    at /<path>/functions/lib/functions/src/index.js:79:64
    at /<path>/functions/node_modules/firebase-functions/lib/v2/providers/https.js:57:29
    at cors (/<path>/functions/node_modules/cors/lib/index.js:188:7)
    at /<path>/functions/node_modules/cors/lib/index.js:224:17
    at originCallback (/<path>/functions/node_modules/cors/lib/index.js:214:15)
    at /<path>/functions/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/<path>/functions/node_modules/cors/lib/index.js:199:9)
```

### Additional information

Similar issue is documented here https://github.com/honojs/node-server/issues/84

As far as I understand the issue occurs in https://github.com/honojs/node-server/blob/3575d60a15e345700b81e22376825e98b0a69ebe/src/listener.ts#L40 . Here the new Request is created from incoming request. 

Firebase use expressjs to process all request and also expose _Express JS Request_ object as an _incoming_. However this request is already "processed" and the actual body stream is already read. 

So when on line https://github.com/honojs/node-server/blob/3575d60a15e345700b81e22376825e98b0a69ebe/src/listener.ts#L38 the read stream is create there is nothing to read. 

I am not sure if this is an issue of Hono or how to approach it. 

My workaround is to patch listner file and restore body from rawBody.
```ts
diff --git a/node_modules/@hono/node-server/dist/listener.js b/node_modules/@hono/node-server/dist/listener.js
index 3f5eaf7..e3541d0 100644
--- a/node_modules/@hono/node-server/dist/listener.js
+++ b/node_modules/@hono/node-server/dist/listener.js
@@ -38,7 +38,14 @@ const getRequestListener = (fetchCallback) => {
       headers: headerRecord
     };
     if (!(method === "GET" || method === "HEAD")) {
-      init.body = import_node_stream.Readable.toWeb(incoming);
+      // init.body = import_node_stream.Readable.toWeb(incoming);
+      init.body = new ReadableStream({
+        start(controller){
+          controller.enqueue(incoming.rawBody);
+          // controller.enqueue('{"c":"d"}');
+            controller.close();
+        }
+      });
       init.duplex = "half";
     }
     let res;

```

**Comment by yusukebe** [comment]
Hi @RobertSasak,

Thank you for creating this. Since it's an issue with `@hono/node-server` (it's fine to create the issue here), could you first provide the version number of your `@hono/node-server`?

**Comment by RobertSasak** [comment]
Originaly I tested on _1.2.0_. I have updated to _1.2.2_ just now and the issue still occurs.

**Comment by AverageHelper** [comment]
I'm having this issue as well. Seems to have to do with that `Readable.toWeb` call.

Tested on Node 18.17.1, hono 3.10.2, @hono/node-server 1.2.3.

**Comment by AverageHelper** [comment]
The above workaround doesn't seem to work in my case. The `Request` gets constructed just fine, but when my handler calls `c.req.json()`, a `TypeError: Received non-Uint8Array chunk` is thrown.

**Comment by ZanzyTHEbar** [comment]
any head-way on this?

**Comment by HananoshikaYomaru** [comment]
c.req.json() and c.req.valid("json") don't work and make it almost unusable.

**Comment by noidwasavailable** [comment]
Is there an update to this?

Looks like this might be related to: https://github.com/vercel/next.js/issues/50166 and https://github.com/FirebaseExtended/firebase-framework-tools/pull/122

**Comment by cogoo** [comment]
I had this identical issue with using vercel funcitons.

I found a solution that might help you further debug the problem.

A similar issue highlights the code in the vercel dev serve that causese the issue:
https://github.com/honojs/node-server/issues/84#issuecomment-1844850121

The issue can be resolved by setting the following environment variable in your local environment file:
```
NODEJS_HELPERS="0"
```

It might be worth checking if Firebase Functions has similar behaviour

**Comment by yusukebe** [comment]
Hi. Is this problem still happening? I don't have an environment for Firebase. If it's not resolved, I'll make it and try to investigate.

**Comment by remorses** [comment]
This problem still happens when you cancel a request that is in progress

**Comment by Bobetti** [comment]
has the exact same error using npm - 10.5.0, "vercel": "^35.2.3", "hono": "^4.5.1",  "@hono/node-server": "^1.12.0",
Switched over to bun, no such error anymore.

**Comment by Bobetti** [comment]
I also noticed that if i turn off  cors middleware, and the post route looks like this:
`    .post("/pricing", async (c) => {
        console.log("post pricing...");

        // const body = await c.req.json();

        return c.json({ success: true });
    });`

Everything works. 

But as soon as I turn on cors - I get the error: "Response body object should not be disturbed or locked".
If I turn off cors but uncomment the above line  ` const body = await c.req.json();`  i get the same error.

**Comment by Bobetti** [comment]
@yusukebe As I see, no responses in this thread. Does it mean, that HonoJs is just not compatible with Vercel's node js environment? And there is no point in waiting for the fast solution and better to move to another framework?

- Tried Elysia JS, but they have errors in sample code which are not fixed for half a year: https://github.com/elysiajs/eden/issues/45
- Tried Fastify JS, but they have compatibility issues with vercel typescript versions: https://github.com/fastify/fastify/issues/5639
- Tried Hono JS: but current error doesn't allow to move forward with the development
- Next is Nest JS. Let's find out what I can find there...

**Comment by yusukebe** [comment]
@Bobetti 

Sorry for the lack of response. If you can share a minimal repo to reproduce it, I can investigate.

**Comment by Bobetti** [comment]
@yusukebe 
Here is the minimal project: https://www.dropbox.com/scl/fi/4qwy7ckiql8uiu8cyr4ot/hono-vercel.zip?rlkey=trq71faz162w5zbpk2rptb6q2&dl=0

I removed vercel info and node modules.



Request I'm sending from svelte application using this code (using hono RPC):

```
const makeRequest = async () => {

		console.log('makeRequest');


		try {
			const dataClient = hc<ApiPricingRoutes>('/');
			const api = dataClient.api;
			const res = await api.pricing.$post({
				json: {
					countryCode: 'Estonia',
					startDateUtc: '2024-07-25T21:00:00.000Z',
					endDateUtc: '2024-07-26T20:59:59.999Z'
				}
			});

			if (!res.ok) {
				const errorText = 'Request failed: ' + res.statusText;
				toast.error(errorText);
				return;
			}

			const result = await res.json();
			toast.success('Request successful: ');
		} catch (error) {
			console.error('There was a problem with the fetch operation:', error);
		}
	};

```


Thank you very much for your help @yusukebe

**Comment by yusukebe** [comment]
@Bobetti 

I've tried it, but I can't understand how to reproduce it. And this project is not minimal. I'm sorry, but I can't help you.

**Comment by Bobetti** [comment]
@yusukebe What does it mean you can't reproduce it? I tried it using macbook M2 air, I tried it using windows 10 machine. Always the same result. I even installed Thunder Client in VS Code to make requests without svelte client. And the result is always the same:
![image](https://github.com/user-attachments/assets/a1ce225e-786d-44e1-8779-fcdc92dc5acb)

Is it really working for you? 
Did you use vercel node.js, see after nr 4,  as written here: https://hono.dev/docs/getting-started/vercel

Exactly the same request in Thunder client, working perfectly using NestJS.

May be you need some more data?

**Comment by yusukebe** [comment]
Hi @Bobetti 

Sorry, it is reproduced. This is a Vercel matter. The stream of `IncomingMessage` from Vercel has already been used. The reason for this is that `incoming.complete` is `true`. I thought we could prevent it with the option `NODEJS_HELPERS=0`, but it does not affect it. This is Vercel matter, so it's difficult to fix it in Hono-side.

**Comment by maxweisel** [comment]
We're hitting this same issue (we do not use vercel or other middleware that adds helpers). It seems specific to sockets getting closed while the request handler is still trying to fulfill the request. Specifically canceling existing requests leads to this bug:

```
node:internal/deps/undici/undici:5312
          throw new TypeError(
          ^

TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:5312:17)
    at new Request (node:internal/deps/undici/undici:9492:48)
    at new Request (file:///usr/src/app/node_modules/@hono/node-server/dist/index.mjs:29:5)
    at newRequestFromIncoming (file:///usr/src/app/node_modules/@hono/node-server/dist/index.mjs:60:10)
    at [getRequestCache] (file:///usr/src/app/node_modules/@hono/node-server/dist/index.mjs:81:35)
    at [getAbortController] (file:///usr/src/app/node_modules/@hono/node-server/dist/index.mjs:76:26)
    at ServerResponse.<anonymous> (file:///usr/src/app/node_modules/@hono/node-server/dist/index.mjs:404:34)
    at ServerResponse.emit (node:events:519:28)
    at emitCloseNT (node:_http_server:1020:10)
    at TLSSocket.onServerResponseClose (node:_http_server:278:5)
```

This is running in docker on linux.

**Comment by yusukebe** [comment]
Hi @maxweisel 

Can you provide a minimal project to reproduce it? It's better it work on my MacOS machine(not on docker) if possible.

**Comment by ivank** [comment]
Also experiencing this when functions are deployed to google functions.

```ts
import { getRequestListener } from '@hono/node-server';
import { http } from '@google-cloud/functions-framework';
import { app } from './app';

http('handler', getRequestListener(app.fetch));
```

With the following code, any post is not working when deployed to google functions (gen2). 
I think it is the way google "prefetches" the data for the functions rather than streaming it in.

**Comment by elct9620** [comment]
I have the same issue on Vercel, there are some test cases to reproduce it.

### ✅ Do nothing
```ts
app.post("/debug", (c) => {
    return c.json({});
});
```

### ✅ Print context

```ts
app.post("/debug", (c) => {
    console.log(c);
    return c.json({});
});
```

### :x: Print request

```ts
app.post("/debug", (c) => {
    console.log(c.req);
    return c.json({});
});
```

> I want to process `c.req.json()` to get the request body but Hono cannot build `c.req`, the error message is `Error: TypeError: Response body object should not be disturbed or locked`

### ✅ Use `c.env.incoming.body`

To verify the `bodyParser` is disabled correctly, I tried another way when I printed context.

```ts
app.post("/debug", (c) => {
    console.log(c.env.incoming.body);
    return c.json({});
});
```

The body is an object depending on the request method.

* `curl localhost:3000 --data '{}'` => `[Object: null prototype] { '{}': '' }`
* `curl localhost:3000 --data '{}' --H 'Content-Type: application/json'` => `{}`

Then, I expected the `bodyParser` isn't disabled. According to [this discussion](https://github.com/vercel/next.js/discussions/58991#discussioncomment-7689055) in Next.js. I guess Vercel expects us to process it twice.

My environment is

```ts
// index.ts

// ...
export const config = {
    api: {
        bodyParser: false,
    },
};

export default handle(app);
```

And build with `tsup --entry.index src/index.ts --clean --format cjs --out-dir api` and I am sure the `api/index.js` is exported `config`

```js
// ...

// src/index.ts
var import_vercel = require("@hono/node-server/vercel");
var config = {
  api: {
    bodyParser: false
  }
};
var src_default = (0, import_vercel.handle)(app_default);
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  config
});
```

**Comment by techwithanirudh** [comment]
Hi, @yusukebe! I'm having a similar issue while using hono and deploying to firebase functions.

Any help would be appreciated!

**Comment by walker-tx** [comment]
@elct9620 The steps detailed in your update worked for me! Thank you!!

**Comment by NicoAcosta** [comment]
I'm still encountering the same issue while using Hono with Firebase Functions. Has anyone found a solution for Firebase?

**Comment by pastak** [comment]
I have faced the same issue on Node. 

The minimum repro is here: 

```
import { Hono } from "hono";
import { serve } from "@hono/node-server";
import { setTimeout } from "node:timers/promises";

const app = new Hono();
app.post("/debug", async (c) => {
  await setTimeout(100000);
  return c.json({});
});

const port = 8080;
serve(
  {
    fetch: app.fetch,
    port,
  },
  (addr) => {
    console.log(`Server is running on http://localhost:${addr.port}`);
  },
);

```

1. Run this code
2. Excecute `curl localhost:8080/debug -XPOST`
3. Abort curl ( ex:  ^C ) after about 3-5 seconds after execute curl.

**Comment by lord007tn** [comment]
same error but when am using openai package to communicate thousands of requests in batches 
i think its a matter of the server didn't response for a long period of time

**Comment by g-mero** [comment]
same issue here.

**Comment by wiredmatt** [comment]
@yusukebe This is also happening when running with the NodeJS adapter `@hono/node-server`.

**Comment by yusukebe** [comment]
@wiredmatt How can I reproduce it? If you provide a minimal project to reproduce it, I can investigate it.

**Comment by motemen** [comment]
Hello, I was likely able to reproduce the issue in the test:

https://github.com/motemen/node-server/commit/2703604db843fdcee9392d6c48fe53aea2f5f0e9

Running this test on my machine (nodejs v22.13.0) produces the following error (though the test itself may pass):

```
TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:5567:17)
    at new Request (node:internal/deps/undici/undici:9783:48)
    at new Request (/Users/motemen/dev/src/github.com/honojs/node-server/src/request.ts:35:9)
    at newRequestFromIncoming (/Users/motemen/dev/src/github.com/honojs/node-server/src/request.ts:67:12)
    at Request.[getRequestCache] (/Users/motemen/dev/src/github.com/honojs/node-server/src/request.ts:88:40)
    at Request.[getAbortController] (/Users/motemen/dev/src/github.com/honojs/node-server/src/request.ts:83:30)
    at ServerResponse.<anonymous> (/Users/motemen/dev/src/github.com/honojs/node-server/src/listener.ts:146:54)
    at ServerResponse.emit (node:events:524:28)
    at emitCloseNT (node:_http_server:1033:10)
    at Socket.onServerResponseClose (node:_http_server:284:5)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:351:12)
```

I believe this happens when the `outgoing.on('close')` callback is executed WITHOUT `req[getRequestCache]` being called beforehand.

**Comment by yusukebe** [comment]
Hi @motemen 

Thank you for the comment and the code.

I think it's natural that the `undici` throws an error when the fetch handler includes a Promise that is never resolved (though the error message may not be friendly).

Hey @usualoma, What do you think of this?

**Comment by usualoma** [comment]
@yusukebe 
Sorry, I'm late; I'll check; give me a minute.

**Comment by shriharip** [comment]
Hi, I am facing the same issue with firebase functions and wanted to metion it is not just related to vercel. I am using the ```@hono/node-server```  .
my typescript config is 
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "baseUrl": "./",
    "paths": {
			"@/*": ["src/*"]
		}
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

and the code
```
const app = new Hono();

app.use(etag(), honoLogger(), cors());


 app.post('/create-merchant', async (c) => {
		const data = await createMerchant(c);
		return c.json(data)
	})

export const api = onRequest({region: 'europe-west3'}, getRequestListener(app.fetch));
```
My package.json
```
  "engines": {
    "node": "22"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/functions-framework": "^3.4.5",
    "@hono/node-server": "^1.13.7",
    "firebase-admin": "^13.0.2",
    "firebase-functions": "^6.3.0",
    "hono": "^4.6.18"
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0",
    "typescript": "^5.7.3"
  },
```

**Comment by usualoma** [comment]
Hi @motemen!
Thank you very much for the example test. I now understand the situation!

And... thank you to @yusukebe  and everyone who has left a comment here.
I think that issue will be fixed in #221.

**Comment by yusukebe** [comment]
@usualoma Thank you for the PR!

I'm working on reviewing https://github.com/honojs/node-server/pull/221. But I want to know the PR can fix the real-world problem before merging. I tried to reproduce the bug of this issue that the app with `@hono/node-server` will throw an error on Firebase Functions deployment when receiving a POST request with the body as [@RobertSasak mentioned](https://github.com/honojs/hono/issues/1695#issue-1992492062). It is reproduced with the current `@hono/node-server@1.13.7`. I also deployed an app with PR https://github.com/honojs/node-server/pull/221 by @usualoma , but it still throws the error. This means the PR can't fix this issue, at least as far as I've tried.

Hi @motemen 

Can you share the real-world problem that you encountered? It's about Firebase Functions?

**Comment by yusukebe** [comment]
I don't think only one specific issue may be throwing the following error message.

```
Response body object should not be disturbed or locked
```

It's possible that there will be a different problem, though the error message is the same.

**Comment by usualoma** [comment]
Sorry, I didn't read the comments at the beginning of the issue properly.

In the case of firebase functions, the body is always consumed in the POST request, so we need to use this `rawBody` that is passed from firebase functions?

https://firebase.google.com/docs/reference/functions/firebase-functions.https.request

**Comment by shriharip** [comment]
@usualoma , Thanks checked it and it is working fine with `rawBody`

**Comment by usualoma** [comment]
I've created https://github.com/honojs/node-server/pull/223

**Comment by motemen** [comment]
> Can you share the real-world problem that you encountered? It's about Firebase Functions?
> https://github.com/honojs/hono/issues/1695#issuecomment-2614323408

Ah... sorry for my late reply @yusukebe,

The problem I encountered was on my local hono/node-server with hono/streaming's `streamSSE`.
I sometimes got the "Response body object should not be disturbed or locked" error when I disconnected from the stream (if I remember correctly), which I think should be resolved by https://github.com/honojs/node-server/pull/221. Thanks!

**Comment by yusukebe** [comment]
@motemen Okay! Thank you!

**Comment by fnandogp** [comment]
Thank you all for having a look at this. I have just stumbled upon this exact problem.

From what I could see, there were no new releases for `@hono/node-server` since the PRs were merged.

Are there any plans to release a new version?
