### ISSUE TITLE
req.valid Argument of type 'string' is not assignable to parameter of type 'never'.

### ISSUE THREAD

**Issue by sysmat** [honojs/hono#1876]
### What version of Hono are you using?

v3.11.11

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

```typescript
const idShema = z
  .string({
    description: "path parameter must be a integer",
    required_error: "id is required",
    invalid_type_error: "must be a number",
  })
  .pipe(z.coerce.number().min(1).max(2147483647))
  .optional();

const idSchema = z.object({
  id: idShema,
});
const idValidator = zValidator("param", idSchema);

reservation.get("/:id", idValidator, async (c: Context) => {
  const { id } = c.req.valid("param");
  ...
});
```

### What is the expected behavior?

- deno-ts  to infer type
- the same error when using `c.req.valid("form")`

### What do you see instead?

- deno error
```json
[{
	"resource": "/api/reservation.ts",
	"owner": "deno",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'string' is not assignable to parameter of type 'never'.",
	"source": "deno-ts",
	"startLineNumber": 60,
	"startColumn": 29,
	"endLineNumber": 60,
	"endColumn": 36,
	"relatedInformation": [
		{
			"startLineNumber": 187,
			"startColumn": 3,
			"endLineNumber": 187,
			"endColumn": 8,
			"message": "The call would have succeeded against this implementation, but implementation signatures of overloads are not externally visible.",
			"resource": "/x/hono@v3.11.11/request.ts"
		}
	]
}]
```

### Additional information

I look at:

- https://github.com/honojs/hono/pull/1351
- https://github.com/orgs/honojs/discussions/1050?sort=new#discussioncomment-5772376

but not working

**Comment by yusukebe** [comment]
Hi @sysmat 

I'm not sure where the error is coming from, but please don't specify `Context` explicitly.

```ts
reservation.get('/:id', idValidator, async (c) => {
  const { id } = c.req.valid('param')
  //...
})
```

And if that does not solve the problem, there may be other causes, which are probably not bugs in Hono. The following code works correctly.

```ts
import { Hono } from 'npm:hono'
import { zValidator } from 'npm:@hono/zod-validator'
import { z } from 'npm:zod'

const app = new Hono()

const idShema = z
  .string({
    description: 'path parameter must be a integer',
    required_error: 'id is required',
    invalid_type_error: 'must be a number'
  })
  .pipe(z.coerce.number().min(1).max(2147483647))
  .optional()

const idSchema = z.object({
  id: idShema
})
const idValidator = zValidator('param', idSchema)

app.get('/:id', idValidator, async (c) => {
  const { id } = c.req.valid('param')
  //...
})

Deno.serve(app.fetch)
```

**Comment by sysmat** [comment]
- but than c is any and not good practice for types and code complition
- yes the route works in runtime, but DX is the problem

**Comment by sysmat** [comment]
Yes it is not a bug, maybe as better DX

**Comment by yusukebe** [comment]
> but than c is any and not good practice for types and code completion

`c` should not be `any`. So maybe your code or setting is wrong. Deno can cause problems if they do not refer to the same `hono` file

**Comment by sysmat** [comment]
So what then c should be?

**Comment by sysmat** [comment]
```
app.get('/:id', idValidator, async (c) => {
  const { id } = c.req.valid('param')
  //...
})
```

in this why deno-tsc telling me, c is any and then I don't have code completion, which is terrible DX

**Comment by sysmat** [comment]
it is much better DX with node

**Comment by yusukebe** [comment]
Try this code:

```ts
import { Hono } from 'npm:hono'
import { zValidator } from 'npm:@hono/zod-validator'
import { z } from 'npm:zod'

const app = new Hono()

const idShema = z
  .string({
    description: 'path parameter must be a integer',
    required_error: 'id is required',
    invalid_type_error: 'must be a number'
  })
  .pipe(z.coerce.number().min(1).max(2147483647))
  .optional()

const idSchema = z.object({
  id: idShema
})
const idValidator = zValidator('param', idSchema)

app.get('/:id', idValidator, async (c) => {
  const { id } = c.req.valid('param')
  //...
})

Deno.serve(app.fetch)
```

**Comment by sysmat** [comment]
- in Node.js v18.19.0 I have other troubles:

```
> tsx watch src/index.ts

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './zod-validator' is not defined by "exports" in C:\Users\tomaz\Projekti\GitHub\hono\node_modules\hono\package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at a._resolveFilename (C:\Users\tomaz\Projekti\GitHub\hono\node_modules\.pnpm\tsx@4.7.0\node_modules\tsx\dist\cjs\index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at reservation (c:\Users\tomaz\Projekti\GitHub\hono\src\api\reservation.ts:2:28)
    at Object.<anonymous> (c:\Users\tomaz\Projekti\GitHub\hono\src\api\reservation.ts:88:16)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (C:\Users\tomaz\Projekti\GitHub\hono\node_modules\.pnpm\tsx@4.7.0\node_modules\tsx\dist\cjs\index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at myJsx (c:\Users\tomaz\Projekti\GitHub\hono\src\app.ts:5:25)
    at Object.<anonymous> (c:\Users\tomaz\Projekti\GitHub\hono\src\app.ts:50:16)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (C:\Users\tomaz\Projekti\GitHub\hono\node_modules\.pnpm\tsx@4.7.0\node_modules\tsx\dist\cjs\index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at app (c:\Users\tomaz\Projekti\GitHub\hono\src\index.ts:2:17)
    at Object.<anonymous> (c:\Users\tomaz\Projekti\GitHub\hono\src\index.ts:10:2)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.S (C:\Users\tomaz\Projekti\GitHub\hono\node_modules\.pnpm\tsx@4.7.0\node_modules\tsx\dist\cjs\index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

- "hono": "^3.11.12" is it PROCUCTION ready?

**Comment by sysmat** [comment]
even in nodejs the same problem with `c.req.valid("param");
` Argument of type 'string' is not assignable to parameter of type 'never'.

```
[{
	"resource": "/C:/Users/tomaz/Projekti/GitHub/hono/src/api/reservation.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'string' is not assignable to parameter of type 'never'.",
	"source": "ts",
	"startLineNumber": 55,
	"startColumn": 30,
	"endLineNumber": 55,
	"endColumn": 37
}]
```
