### ISSUE TITLE
Multiple optional parameters - are they supposed to work?

### ISSUE THREAD

**Issue by leonlarsson** [honojs/hono#1925]
### What version of Hono are you using?

3.12.0

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

Create a minimal Hono app (this is running on Cloudflare Workers)
```ts
import { Hono } from "hono";

const app = new Hono();

app.get("/base/:firstoptional?/:secondoptional?", c => c.json(c.req.param()));
// /base ->                     404 (why?)
// /base/hello ->               { "firstoptional?": "hello" }
// /base/hello/world ->         { "secondoptional": "world", "firstoptional?": "hello" }

export default app;

```

### What is the expected behavior?

- I would expect `/base` to match
- I would expect it to not return `?` in the param key names

### What do you see instead?

I see what I have commented in the code. The `?` is added to the param key name.

### Additional information

My real life use-case is:
```ts
app.get("/v1/leaderboard/:version?/:platform?", handler);
```
This acts in the same as the above examples.
I would like to be able to match `/v1/leaderboard` and then handle if the params are undefined.

If this is intended (I can understand the reasons for being intentional), then this might be seen as a feature request.

**Comment by leonlarsson** [comment]
I have updated to 3.12.2, and now I have a different error.

Using the same sample application as above, I get HTTP 500 errors on every request where there is a route with multiple optional params:
```
[wrangler:err] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at null.<anonymous> (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/reg-exp-router/router.js:55:30)
    at [object Object]
    at buildMatcherFromPreprocessedRoutes (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/reg-exp-router/router.js:51:31)
    at RegExpRouter.buildMatcher (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/reg-exp-router/router.js:204:14)
    at null.<anonymous> (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/reg-exp-router/router.js:182:31)
    at [object Object]
    at RegExpRouter.buildAllMatchers (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/reg-exp-router/router.js:181:17)
    at RegExpRouter.match (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/reg-exp-router/router.js:163:27)
    at SmartRouter.match (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/router/smart-router/router.js:30:22)
    at Hono2.matchRoute (file:///C:/Users/leonl/Desktop/Projects/the-finals-api/node_modules/hono/dist/hono-base.js:206:24)
[wrangler:inf] GET / 500 Internal Server Error (26ms)
```

**Comment by leonlarsson** [comment]
@yusukebe ping for visibility

**Comment by yusukebe** [comment]
@leonlarsson 

Thanks for your response.

@usualoma 

Sorry for pinging you again and again.

I've not tested enough, but the changes in #1940 seem to cause unexpected behavior with RegExpRouter and LinearRouter.

I added tests in the following branch, and you can run them. If you would like, I would appreciate it if you could make a PR from this branch and fix it.

https://github.com/honojs/hono/tree/test/add-optional-params-tests

**Comment by usualoma** [comment]
@yusukebe 
This will fix it, so it would be helpful if you could fix it and have it done!

```diff
diff --git a/src/router/linear-router/router.ts b/src/router/linear-router/router.ts
index dd1afe75..7d91554f 100644
--- a/src/router/linear-router/router.ts
+++ b/src/router/linear-router/router.ts
@@ -1,5 +1,6 @@
 import type { Router, Result, Params } from '../../router'
 import { METHOD_NAME_ALL, UnsupportedPathError } from '../../router'
+import { checkOptionalParameter } from '../../utils/url'
 
 type RegExpMatchArrayWithIndices = RegExpMatchArray & { indices: [number, number][] }
 
@@ -12,13 +13,9 @@ export class LinearRouter<T> implements Router<T> {
   routes: [string, string, T][] = []
 
   add(method: string, path: string, handler: T) {
-    if (path.charCodeAt(path.length - 1) === 63) {
-      // /path/to/:label? means /path/to/:label or /path/to
-      this.routes.push([method, path.slice(0, -1), handler])
-      this.routes.push([method, path.replace(/\/[^/]+$/, ''), handler])
-    } else {
-      this.routes.push([method, path, handler])
-    }
+    ;(checkOptionalParameter(path) || [path]).forEach((p) => {
+      this.routes.push([method, p, handler])
+    })
   }
 
   match(method: string, path: string): Result<T> {
diff --git a/src/router/reg-exp-router/router.ts b/src/router/reg-exp-router/router.ts
index 82a8d0ea..a6d6009f 100644
--- a/src/router/reg-exp-router/router.ts
+++ b/src/router/reg-exp-router/router.ts
@@ -198,10 +198,7 @@ export class RegExpRouter<T> implements Router<T> {
               findMiddleware(middleware[METHOD_NAME_ALL], path) ||
               []),
           ]
-          routes[m][path].push([
-            handler,
-            paths.length === 2 && i === 0 ? paramCount - 1 : paramCount,
-          ])
+          routes[m][path].push([handler, paths.length > 1 ? i : paramCount])
         }
       })
     }
```

**Comment by yusukebe** [comment]
@usualoma 

Thanks! I've created the PR with your patch. But, one test fails. Could you see it?

https://github.com/honojs/hono/pull/1951

**Comment by usualoma** [comment]
@yusukebe Sorry!

```ts
diff --git a/src/router/reg-exp-router/router.ts b/src/router/reg-exp-router/router.ts
index a6d6009f..69dc8eec 100644
--- a/src/router/reg-exp-router/router.ts
+++ b/src/router/reg-exp-router/router.ts
@@ -198,7 +198,7 @@ export class RegExpRouter<T> implements Router<T> {
               findMiddleware(middleware[METHOD_NAME_ALL], path) ||
               []),
           ]
-          routes[m][path].push([handler, paths.length > 1 ? i : paramCount])
+          routes[m][path].push([handler, len > 1 ? paramCount - len + i + 1 : paramCount])
         }
       })
     }
```

**Comment by usualoma** [comment]
Or maybe even simpler.
```diff
diff --git a/src/router/reg-exp-router/router.ts b/src/router/reg-exp-router/router.ts
index a6d6009f..51ab473e 100644
--- a/src/router/reg-exp-router/router.ts
+++ b/src/router/reg-exp-router/router.ts
@@ -198,7 +198,7 @@ export class RegExpRouter<T> implements Router<T> {
               findMiddleware(middleware[METHOD_NAME_ALL], path) ||
               []),
           ]
-          routes[m][path].push([handler, paths.length > 1 ? i : paramCount])
+          routes[m][path].push([handler, paramCount - len + i + 1])
         }
       })
     }
```

**Comment by yusukebe** [comment]
@usualoma 

Thank you for the quick response. Merged https://github.com/honojs/hono/pull/1951

**Comment by leonlarsson** [comment]
Thanks for your work. I can confirm this works properly now :)
