### ISSUE TITLE
html renderer `isEscaped` TypeError

### ISSUE THREAD

**Issue by bpevs** [honojs/hono#2194]
### What version of Hono are you using?

4.0.1

### What runtime/platform is your app running on?

deno 1.40.4 (release, aarch64-apple-darwin)

### What steps can reproduce the bug?

I'm trying to transition an open-source pet project from preact to hono.

Running the project via that branch (`deno task dev`), `html` is throwing an error when I try to render to html string:
https://github.com/bpevs/fridaypoetry.org/blob/feat/hono/source/components/html.tsx#L16

Rendered via this route:
https://github.com/bpevs/fridaypoetry.org/blob/feat/hono/source/main.tsx#L30

### What do you see instead?

```
TypeError: Cannot read properties of null (reading 'isEscaped')
    at JSXFunctionNode.toStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:218:64)
    at childrenToStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:79:13)
    at JSXNode.toStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:185:5)
    at childrenToStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:79:13)
    at JSXFragmentNode.toStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:228:5)
    at JSXFunctionNode.toStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:217:11)
    at JSXFunctionNode.toStringToBuffer (https://deno.land/x/hono@v4.0.1/jsx/base.ts:217:11)
    at JSXFunctionNode.toString (https://deno.land/x/hono@v4.0.1/jsx/base.ts:115:12)
    at html (https://deno.land/x/hono@v4.0.1/helper/html/index.ts:28:27)
    at Html (file:///Users/ben/Vault/20-29%20Projects/20%20Code/20.09%20fridaypoetry.org/source/components/html.tsx:16:14)
```

### Additional information

Going straight from Preact to Hono 4.x.x, so this may be user error / I'm not sure if the expected api is now different from [honojs/examples](https://github.com/honojs/examples/tree/main/deno), which is running 3.x.x

**Comment by bpevs** [comment]
Was caused by a component that returns children w/o wrapping in Fragment.  I guess it's valid in Preact, but not Hono.

https://github.com/bpevs/fridaypoetry.org/blob/2ae43fa7c0b8d41546261e6553aac012ee904d88/source/components/only.tsx#L11
