### ISSUE TITLE
Improve test execution speed on WSL

### ISSUE THREAD

**Issue by ryuapp** [honojs/hono#2221]
### Run test time
OS: Windows10(Ubuntu20.04)
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
- `bun run test`: 75.70 + 14.62 + 12.58 = 102.9s
- `yarn test`: 7.85 + 2.30 + 2.10 = 12.25s

<details>

<summary>Bun logs</summary>

```sh
xxxxx@yyyyy:/mnt/c/Users/xxxxx/repo/hono$ bun run test
$ tsc --noEmit && vitest --run && vitest -c .vitest.config/jsx-runtime-default.ts --run && vitest -c .vitest.config/jsx-runtime-dom.ts --run

 RUN  v1.2.2 /mnt/c/Users/xxxxx/repo/hono

stdout | src/hono.test.ts > Middleware > Basic > logging and custom header
GET : http://localhost/hello

stdout | src/hono.test.ts > Middleware > Basic > logging and custom header with named param
GET : http://localhost/hello/message

stdout | src/hono.test.ts > Middleware > Basic > should return correct the content-type header
GET : http://localhost/json

stdout | src/hono.test.ts > Middleware > Basic > not found
GET : http://localhost/foo

stdout | src/hono.test.ts > Middleware > Basic > internal server error
GET : http://localhost/error
Internal Server Error

stderr | src/hono.test.ts > Middleware > Basic > internal server error
Error: Error!
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:973:13
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:46:20
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:930:13
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:46:20
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:925:13
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:18:12
    at /mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:357:31

stderr | src/hono.test.ts > Error handling in middleware > Should handle the error in middleware
Error: Error message
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:1400:11
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:46:20
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:1381:11
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:18:12
    at /mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:357:31
    at Hono.dispatch (/mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:368:5)
    at Hono.fetch (/mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:376:17)
    at Hono.request (/mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:406:17)

stderr | src/hono.test.ts > Error handling in middleware > Should handle the error in middleware - async
Error: Error message
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:1404:11
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:46:20
    at /mnt/c/Users/xxxxx/repo/hono/src/hono.test.ts:1389:11
    at dispatch (/mnt/c/Users/xxxxx/repo/hono/src/compose.ts:45:23)
    at /mnt/c/Users/xxxxx/repo/hono/src/compose.ts:18:12
    at /mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:357:31
    at Hono.dispatch (/mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:368:5)
    at Hono.fetch (/mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:376:17)
    at Hono.request (/mnt/c/Users/xxxxx/repo/hono/src/hono-base.ts:406:17)

stdout | src/helper/ssg/index.test.tsx > toSSG function > should execute additional processing using afterGenerateHook
static/index.html
static/about.html
static/about/some.txt
static/bravo.html
static/Charlie.html
static/post/1.html
static/post/2.html
static/user/1.html
static/user/2.html
static/user/3.html

stderr | src/jsx/streaming.test.tsx > Streaming > reject()
Trace: undefined
    at /mnt/c/Users/xxxxx/repo/hono/src/jsx/streaming.ts:137:23
    at async Promise.all (index 0)
    at Object.start (/mnt/c/Users/xxxxx/repo/hono/src/jsx/streaming.ts:158:9)

 ✓ src/router/trie-router/node.test.ts (77)
 ✓ src/router/pattern-router/router.test.ts (52)
 ✓ src/router/reg-exp-router/router.test.ts (60)
 ✓ src/compose.test.ts (31)
 ✓ src/validator/validator.test.ts (30)
 ✓ src/hono.test.ts (179) 489ms
 ✓ src/jsx/index.test.tsx (62)
 ↓ src/helper/css/common.test.tsx (1) [skipped]
 ✓ src/helper/ssg/index.test.tsx (24)
 ✓ src/types.test.ts (38)
 ✓ src/client/client.test.ts (28)
 ✓ src/jsx/streaming.test.tsx (17) 503ms
 ✓ src/jsx/dom/index.test.tsx (49) 866ms
 ✓ src/router/linear-router/router.test.ts (34)
 ✓ src/helper/cookie/index.test.ts (17)
 ✓ src/utils/url.test.ts (15)
 ✓ src/middleware/jsx-renderer/index.test.tsx (11)
 ✓ src/context.test.ts (30)
 ✓ src/middleware/secure-headers/index.test.ts (10)
 ✓ src/utils/cookie.test.ts (22)
 ✓ src/router/trie-router/router.test.ts (24)
 ✓ src/middleware/csrf/index.test.ts (14)
 ✓ src/request.test.ts (14)
 ✓ src/utils/jwt/jwt.test.ts (10)
 ✓ src/middleware/jwt/index.test.ts (12)
 ✓ src/adapter/cloudflare-workers/serve-static.test.ts (15)
 ✓ src/helper/css/index.test.tsx (36) 741ms
 ✓ src/helper/accepts/accepts.test.ts (8)
 ✓ src/helper/dev/index.test.ts (8)
 ✓ src/middleware/basic-auth/index.test.ts (7)
 ✓ src/jsx/components.test.tsx (18) 307ms
 ✓ src/middleware/bearer-auth/index.test.ts (9)
 ✓ src/middleware/cors/index.test.ts (7)
 ✓ src/jsx/hooks/dom.test.tsx (10) 320ms
 ✓ src/helper/factory/index.test.ts (7)
 ✓ src/utils/stream.test.ts (8)
 ✓ src/middleware/logger/index.test.ts (10) 2065ms
 ✓ src/middleware/etag/index.test.ts (8)
 ✓ src/router/smart-router/router.test.ts (6)
 ✓ src/helper/streaming/sse.test.ts (3) 427ms
 ✓ src/middleware/cache/index.test.ts (6)
 ✓ src/utils/buffer.test.ts (5)
 ✓ src/client/utils.test.ts (7)
 ✓ src/utils/body.test.ts (6)
 ✓ src/utils/filepath.test.ts (1)
 ✓ src/utils/encode.test.ts (44)
 ✓ src/helper/html/index.test.ts (10)
 ✓ src/helper/ssg/utils.test.ts (3)
 ✓ src/middleware/timing/index.test.ts (3)
 ✓ src/utils/types.test.ts (4)
 ✓ src/utils/crypto.test.ts (5)
 ✓ src/middleware/compress/index.test.ts (4)
 ✓ src/utils/mime.test.ts (3)
 ✓ src/adapter/aws-lambda/handler.test.ts (2)
 ✓ src/helper/streaming/text.test.ts (1)
 ✓ src/helper/streaming/stream.test.ts (2)
 ✓ src/jsx/dom/components.test.tsx (16) 506ms
 ✓ src/adapter/vercel/handler.test.ts (2)
 ✓ src/adapter/cloudflare-pages/handler.test.ts (2)
 ✓ src/jsx/jsx-runtime.test.tsx (6)
 ✓ src/adapter/cloudflare-workers/utils.test.ts (1)
 ✓ src/middleware/pretty-json/index.test.ts (2)
 ✓ src/utils/html.test.ts (1)
 ✓ src/adapter/lambda-edge/handler.test.ts (1)
 ✓ src/jsx/dom/context.test.tsx (8)
 ✓ src/helper/testing/index.test.ts (2)
 ✓ src/http-exception.test.ts (1)
 ✓ src/middleware/powered-by/index.test.ts (2)
 ✓ src/utils/jwt/types.test.ts (1)
 ✓ src/helper/adapter/index.test.ts (1)
 ✓ src/jsx/dom/css.test.tsx (27)

 Test Files  70 passed | 1 skipped (71)
      Tests  1193 passed | 7 skipped (1200)
   Start at  00:27:23
   Duration  75.70s (transform 59.87s, setup 27.65s, collect 310.53s, tests 9.35s, environment 36ms, prepare 291.23s)


 RUN  v1.2.2 /mnt/c/Users/xxxxx/repo/hono

 ✓ src/jsx/dom/index.test.tsx (49) 803ms
 ✓ src/jsx/dom/context.test.tsx (8)
 ✓ src/jsx/hooks/dom.test.tsx (10) 428ms
 ✓ src/jsx/dom/components.test.tsx (16) 358ms
 ✓ src/jsx/dom/css.test.tsx (27)

 Test Files  5 passed (5)
      Tests  106 passed | 4 skipped (110)
   Start at  00:28:45
   Duration  14.62s (transform 4.65s, setup 2.12s, collect 48.46s, tests 2.04s, environment 1ms, prepare 9.41s)


 RUN  v1.2.2 /mnt/c/Users/xxxxx/repo/hono

 ✓ src/jsx/dom/index.test.tsx (49) 744ms
 ✓ src/jsx/hooks/dom.test.tsx (10)
 ✓ src/jsx/dom/context.test.tsx (8)
 ✓ src/jsx/dom/css.test.tsx (27) 665ms
 ✓ src/jsx/dom/components.test.tsx (16) 322ms

 Test Files  5 passed (5)
      Tests  106 passed | 4 skipped (110)
   Start at  00:29:06
   Duration  12.58s (transform 5.31s, setup 1.84s, collect 39.74s, tests 2.20s, environment 1ms, prepare 9.63s)
```

</details>

<details>
<summary>Yarn logs</summary>

```sh
C:\Users\xxxxx\repo\hono>yarn test
yarn run v1.22.19
$ tsc --noEmit && vitest --run && vitest -c .vitest.config/jsx-runtime-default.ts --run && vitest -c .vitest.config/jsx-runtime-dom.ts --run

 RUN  v1.2.2 C:/Users/xxxxx/repo/hono

stdout | src/hono.test.ts > Middleware > Basic > logging and custom header
GET : http://localhost/hello

stdout | src/hono.test.ts > Middleware > Basic > logging and custom header with named param
GET : http://localhost/hello/message

stdout | src/hono.test.ts > Middleware > Basic > should return correct the content-type header
GET : http://localhost/json

stdout | src/hono.test.ts > Middleware > Basic > not found
GET : http://localhost/foo

stdout | src/hono.test.ts > Middleware > Basic > internal server error
GET : http://localhost/error
Internal Server Error

stderr | src/hono.test.ts > Middleware > Basic > internal server error
Error: Error!
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:973:13
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:46:20
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:930:13
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:46:20
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:925:13
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:18:12
    at C:\Users\xxxxx\repo\hono\src\hono-base.ts:357:31

stderr | src/hono.test.ts > Error handling in middleware > Should handle the error in middleware
Error: Error message
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:1400:11
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:46:20
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:1381:11
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:18:12
    at C:\Users\xxxxx\repo\hono\src\hono-base.ts:357:31
    at Hono.dispatch (C:\Users\xxxxx\repo\hono\src\hono-base.ts:368:5)
    at Hono.fetch (C:\Users\xxxxx\repo\hono\src\hono-base.ts:376:17)
    at Hono.request (C:\Users\xxxxx\repo\hono\src\hono-base.ts:406:17)

stderr | src/hono.test.ts > Error handling in middleware > Should handle the error in middleware - async
Error: Error message
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:1404:11
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:46:20
    at C:\Users\xxxxx\repo\hono\src\hono.test.ts:1389:11
    at dispatch (C:\Users\xxxxx\repo\hono\src\compose.ts:45:23)
    at C:\Users\xxxxx\repo\hono\src\compose.ts:18:12
    at C:\Users\xxxxx\repo\hono\src\hono-base.ts:357:31
    at Hono.dispatch (C:\Users\xxxxx\repo\hono\src\hono-base.ts:368:5)
    at Hono.fetch (C:\Users\xxxxx\repo\hono\src\hono-base.ts:376:17)
    at Hono.request (C:\Users\xxxxx\repo\hono\src\hono-base.ts:406:17)

stderr | src/jsx/streaming.test.tsx > Streaming > reject()
Trace: undefined
    at C:\Users\xxxxx\repo\hono\src\jsx\streaming.ts:137:23
    at async Promise.all (index 0)
    at Object.start (C:\Users\xxxxx\repo\hono\src\jsx\streaming.ts:158:9)

stdout | src/helper/ssg/index.test.tsx > toSSG function > should execute additional processing using afterGenerateHook
static/index.html
static/about.html
static/about/some.txt
static/bravo.html
static/Charlie.html
static/post/1.html
static/post/2.html
static/user/1.html
static/user/2.html
static/user/3.html

 ✓ src/router/pattern-router/router.test.ts (52)
 ✓ src/router/trie-router/node.test.ts (77)
 ✓ src/router/reg-exp-router/router.test.ts (60)
 ✓ src/compose.test.ts (31)
 ✓ src/validator/validator.test.ts (30)
 ✓ src/hono.test.ts (179) 398ms
 ✓ src/client/client.test.ts (28)
 ✓ src/jsx/index.test.tsx (62)
 ✓ src/jsx/streaming.test.tsx (17) 657ms
 ↓ src/helper/css/common.test.tsx (1) [skipped]
 ✓ src/jsx/dom/index.test.tsx (49) 1037ms
 ✓ src/types.test.ts (38)
 ✓ src/helper/ssg/index.test.tsx (24)
 ✓ src/router/linear-router/router.test.ts (34)
 ✓ src/middleware/jsx-renderer/index.test.tsx (11)
 ✓ src/jsx/components.test.tsx (18) 394ms
 ✓ src/utils/url.test.ts (15)
 ✓ src/context.test.ts (30)
 ✓ src/helper/cookie/index.test.ts (17)
 ✓ src/utils/cookie.test.ts (22)
 ✓ src/middleware/secure-headers/index.test.ts (10)
 ✓ src/jsx/hooks/dom.test.tsx (10) 397ms
 ✓ src/middleware/csrf/index.test.ts (14)
 ✓ src/router/trie-router/router.test.ts (24)
 ✓ src/request.test.ts (14)
 ✓ src/utils/jwt/jwt.test.ts (10)
 ✓ src/middleware/jwt/index.test.ts (12)
 ✓ src/adapter/cloudflare-workers/serve-static.test.ts (15)
 ✓ src/helper/accepts/accepts.test.ts (8)
 ✓ src/helper/dev/index.test.ts (8)
 ✓ src/helper/css/index.test.tsx (36)
 ✓ src/middleware/cors/index.test.ts (7)
 ✓ src/middleware/basic-auth/index.test.ts (7)
 ✓ src/middleware/bearer-auth/index.test.ts (9)
 ✓ src/jsx/dom/components.test.tsx (16) 622ms
 ✓ src/middleware/etag/index.test.ts (8)
 ✓ src/middleware/logger/index.test.ts (10) 2054ms
 ✓ src/helper/factory/index.test.ts (7)
 ✓ src/utils/stream.test.ts (8)
 ✓ src/router/smart-router/router.test.ts (6)
 ✓ src/middleware/cache/index.test.ts (6)
 ✓ src/helper/streaming/sse.test.ts (3) 429ms
 ✓ src/utils/buffer.test.ts (5)
 ✓ src/client/utils.test.ts (7)
 ✓ src/utils/body.test.ts (6)
 ✓ src/utils/filepath.test.ts (1)
 ✓ src/utils/encode.test.ts (44)
 ✓ src/jsx/dom/context.test.tsx (8) 329ms
 ✓ src/helper/html/index.test.ts (10)
 ✓ src/helper/ssg/utils.test.ts (3)
 ✓ src/middleware/timing/index.test.ts (3)
 ✓ src/middleware/compress/index.test.ts (4)
 ✓ src/utils/crypto.test.ts (5)
 ✓ src/utils/mime.test.ts (3)
 ✓ src/jsx/dom/css.test.tsx (27) 590ms
 ✓ src/utils/types.test.ts (4)
 ✓ src/adapter/cloudflare-pages/handler.test.ts (2)
 ✓ src/adapter/aws-lambda/handler.test.ts (2)
 ✓ src/adapter/vercel/handler.test.ts (2)
 ✓ src/helper/streaming/stream.test.ts (2)
 ✓ src/adapter/cloudflare-workers/utils.test.ts (1)
 ✓ src/helper/streaming/text.test.ts (1)
 ✓ src/adapter/lambda-edge/handler.test.ts (1)
 ✓ src/middleware/pretty-json/index.test.ts (2)
 ✓ src/jsx/jsx-runtime.test.tsx (6)
 ✓ src/middleware/powered-by/index.test.ts (2)
 ✓ src/utils/html.test.ts (1)
 ✓ src/helper/testing/index.test.ts (2)
 ✓ src/http-exception.test.ts (1)
 ✓ src/utils/jwt/types.test.ts (1)
 ✓ src/helper/adapter/index.test.ts (1)

 Test Files  70 passed | 1 skipped (71)
      Tests  1193 passed | 7 skipped (1200)
   Start at  00:30:31
   Duration  7.85s (transform 7.80s, setup 2.32s, collect 24.43s, tests 9.59s, environment 27ms, prepare 20.33s)


 RUN  v1.2.2 C:/Users/xxxxx/repo/hono

 ✓ src/jsx/hooks/dom.test.tsx (10)
 ✓ src/jsx/dom/index.test.tsx (49) 749ms
 ✓ src/jsx/dom/components.test.tsx (16) 370ms
 ✓ src/jsx/dom/context.test.tsx (8)
 ✓ src/jsx/dom/css.test.tsx (27) 385ms

 Test Files  5 passed (5)
      Tests  106 passed | 4 skipped (110)
   Start at  00:30:39
   Duration  2.30s (transform 874ms, setup 96ms, collect 5.19s, tests 2.03s, environment 1ms, prepare 823ms)


 RUN  v1.2.2 C:/Users/xxxxx/repo/hono

 ✓ src/jsx/hooks/dom.test.tsx (10)
 ✓ src/jsx/dom/index.test.tsx (49) 595ms
 ✓ src/jsx/dom/context.test.tsx (8)
 ✓ src/jsx/dom/components.test.tsx (16)
 ✓ src/jsx/dom/css.test.tsx (27)

 Test Files  5 passed (5)
      Tests  106 passed | 4 skipped (110)
   Start at  00:30:42
   Duration  2.10s (transform 1.18s, setup 127ms, collect 4.64s, tests 1.53s, environment 1ms, prepare 1.25s)

Done in 21.50s.
```
</details>

It's too slow so I am testing by replacing `bun run` with `yarn` in package.json
Windows users have difficulty testing Hono with Bun on WSL.
If you use Windows and can test faster, please let me know.
My computer is old.

**Comment by yusukebe** [comment]
@ryuapp 

I see. But I feel it's a little bit weird because we use Bun as just a task runner.

Though, we can still use `yarn`, `bun install` command will emit `yarn.lock`. We can recommend using `yarn` for a Windows user.

**Comment by ryuapp** [comment]
@yusukebe 
You are right. I often use `yarn` in Hono.
To be accurate, we use Bun in `test:all`. So when I run it, I use `yarn` instead.
```diff
-"test:all": "bun run test && bun test:deno && bun test:bun && bun test:fastly && bun test:node && bun test:wrangler && bun test:lambda && bun test:lambda-edge",
+"test:all": "yarn test && yarn test:deno && yarn test:bun && yarn test:fastly && yarn test:node && yarn test:wrangler && yarn test:lambda && yarn test:lambda-edge",
```

**Comment by yusukebe** [comment]
Or we can use `$npm_execpath` or `%npm_execpath%`?

**Comment by yusukebe** [comment]
@ryuapp 

We might consider using Bun only for the package installer and `yarn` for the task runner.

**Comment by ryuapp** [comment]
Thank you for your consideration.

> Or we can use $npm_execpath or %npm_execpath%?

This works on WSL and Windows.
However, using `$npm_execpath` directly does not support Windows.
Therefore, the script like [ni](https://github.com/antfu/ni) for Windows support is required.

**Comment by yusukebe** [comment]
> This works on WSL and Windows.
> However, using `$npm_execpath` directly does not support Windows.

You are right.

Alternatively, we could use `yarn` as a task runner instead of `bun`. Hmmm...

**Comment by sor4chi** [comment]
I don't have Windows, so I can't say for sure, but I'm guessing from the name that `mnt/*` probably does a conversion to the Windows file system every time you write to it, and that's the overhead.
If you do so, I recommend that you always set the working path to a location that is not `mnt/*`, not just Hono.

**Comment by ryuapp** [comment]
@sor4chi 
Thank you for the tip.
I thought I had tested in the past with paths other than `mnt/*`.
But I just tried it again and it was fastest even on Windows!

Bun v1.2.2
`bun run test`: 1.51 + 1.51 + 1.39 = 4.41s.

This issue is resolved, thank you again.
