### ISSUE TITLE
Cannot set property duplex of #<_Request> which has only a getter

### ISSUE THREAD

**Issue by wenerme** [honojs/hono#2267]
### What version of Hono are you using?

4.0.4

### What runtime/platform is your app running on?

node

### What steps can reproduce the bug?

```ts
app.mount('/',(req)=>new Response(new ReadableStream()))
```

```ts
curl http://0.0.0.0:8787/xyz -X OPTIONS
```

### What is the expected behavior?

Works as expected

### What do you see instead?

```
TypeError: Cannot set property duplex of #<_Request> which has only a getter
    at new Request (file:///app/node_modules/.pnpm/@hono+node-server@1.8.1/node_modules/@hono/node-server/dist/index.mjs:15:22)
    at handler (file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/hono-base.js:169:9)
    at dispatch (file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/compose.js:29:23)
    at file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/compose.js:30:20
    at logger2 (file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/middleware/logger/index.js:35:11)
    at dispatch (file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/compose.js:29:23)
    at file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/compose.js:6:12
    at file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/hono-base.js:226:31
    at Hono.dispatch (file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/hono-base.js:236:7)
    at fetch (file:///app/node_modules/.pnpm/hono@4.0.4/node_modules/hono/dist/hono-base.js:60:19)

```

### Additional information

Seems triggered by 

https://github.com/honojs/node-server/blob/826b77bbf0d10c103fd03e66956bbfd1f01c41ea/src/request.ts#L14-L18

But this is not allowed see https://github.com/sindresorhus/ky/issues/467

**Comment by wenerme** [comment]
xref https://github.com/honojs/node-server/pull/149
