### ISSUE TITLE
utils/encode exception in latest release

### ISSUE THREAD

**Issue by metrue** [honojs/hono#248]
Create a issue in case someone found this issue too, I'm trying to find the root-cause. 
```sh
✘ [ERROR] [plugin checkForNodeBuiltins] Detected a Node builtin module import while Node compatibility is disabled.
Add node_compat = true to your wrangler.toml file to enable Node compatibility.

    node_modules/hono/dist/utils/encode.js:42:35:
      42 │         const { Buffer } = require('buffer');
         ╵                                    ~~~~~~~~

  This error came from the "onResolve" callback registered here:

    ../../../../.npm/_npx/dce38835dbc726fc/node_modules/wrangler/wrangler-dist/cli.js:109002:11:
      109002 │     build6.onResolve({
             ╵            ~~~~~~~~~

    at setup (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/wrangler/wrangler-dist/cli.js:109002:12)
    at handlePlugins (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/esbuild/lib/main.js:843:23)
    at Object.buildOrServe (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/esbuild/lib/main.js:1137:7)
    at /Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/esbuild/lib/main.js:2079:17
    at new Promise (<anonymous>)
    at Object.build (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/esbuild/lib/main.js:2078:14)
    at Object.build (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/esbuild/lib/main.js:1927:51)
    at bundleWorker (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/wrangler/wrangler-dist/cli.js:109030:33)
    at build6 (/Users/minhuang/.npm/_npx/dce38835dbc726fc/node_modules/wrangler/wrangler-dist/cli.js:109124:75)


✘ [ERROR] Build failed with 1 error:

  node_modules/hono/dist/utils/encode.js:42:35: ERROR: [plugin: checkForNodeBuiltins] Detected a
  Node builtin module import while Node compatibility is disabled.
  Add node_compat = true to your wrangler.toml file to enable Node compatibility.
```

**Comment by yusukebe** [comment]
Hi @metrue 

How can I reproduce it?

**Comment by yusukebe** [comment]
Hi @metrue 

It is reproduced using Wrangler **2.0.6**.  This error is caused by `dynamic import`.

```ts
  try {
    const { Buffer } = await import('buffer') // <----
    return Buffer.from(String.fromCharCode(...new Uint8Array(buf))).toString('base64')
  } catch (e) {}
```

 I'm planning to remove `dynamic import`. Wait a minute.

**Comment by metrue** [comment]
@yusukebe 

Sorry for late response.

Thank for the fix.
