### ISSUE TITLE
`event` undefined in durable object

### ISSUE THREAD

**Issue by etienne-napoleone** [honojs/hono#311]
Hello, I don't know if this is normal, but when following this pattern for handling Durable objects fetch w/ Hono:

```ts
import { Hono } from 'hono'

export class FooBar {
  state: DurableObjectState
  app: Hono = new Hono()

  constructor(state: DurableObjectState) {
    this.state = state
    this.app.get('/', async (c) => {
      //...
      c.event?.waitUntil(
        this.state.storage?.put('foo', bar),
      )
    } 
  }

  async fetch(request: Request) {
    return this.app.fetch(request)
  }
}
```

It seems that `event?` is undefined because it is never written to storage.

By using `!` instead of `?` i get the confirmation via this error.

```
  (error) TypeError: Cannot read properties of undefined (reading 'waitUntil')
    at index.js:844:15
    at dispatch2 (index.js:219:34)
    at index.js:204:16
    at Hono3.dispatch (index.js:618:27)
    at Hono3.fetch (index.js:634:21)
    at Quota.fetch (index.js:961:21)
```

Is there a way to make the fetch event propagated there?

**Comment by etienne-napoleone** [comment]
ah ok nvm, makes sense it's not defined. should use `state.waitUntil`!
