### ISSUE TITLE
Fragment does'n work in custom JSX Component

### ISSUE THREAD

**Issue by karolskolasinski** [honojs/hono#3235]
### What version of Hono are you using?

4.5.1

### What runtime/platform is your app running on?

Deno

### What steps can reproduce the bug?

- create custom JSX Component 
```ts
function MyComponent() {
  return <></>;
}
```
- use this component
```ts
  return <MyComponent></MyComponent>;
```
and the app crash.

### What is the expected behavior?

should render Fragment without import

### What do you see instead?

```console
2024-08-06T08:11:01.631Z [ERROR] [client] TypeError: Cannot read properties of null (reading 'isEscaped')
    at JSXFunctionNode.toStringToBuffer (https://jsr.io/@hono/hono/4.5.1/src/jsx/base.ts:251:64)
    at JSXFunctionNode.toString (https://jsr.io/@hono/hono/4.5.1/src/jsx/base.ts:143:12)
    at html (https://jsr.io/@hono/hono/4.5.1/src/helper/html/index.ts:35:29)
```

### Additional information

if you import `import { Fragment } from "hono/jsx/jsx-runtime";` it works, but IDE not report any info that something is wrong

**Comment by usualoma** [comment]
Hi @karolskolasinski, Thank you for your report.
I will investigate!
