### ISSUE TITLE
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start.

### ISSUE THREAD

**Issue by WuChenDi** [honojs/hono#3269]
### What version of Hono are you using?

"hono": "^4.5.5"

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

Hello, I have discovered that an error occurred while executing on my machine. Could you please inform me if Hono currently does not support running on Windows machines?

Below are the steps I followed during the execution.

equipment information:
- win 11
- nodejs: v22.1.0
- pnpm: v9.6.0

code

- package.json

```json
{
  "scripts": {
    "dev": "wrangler dev src/index.ts",
    "deploy": "wrangler deploy --minify src/index.ts"
  },
  "dependencies": {
    "hono": "^4.5.5"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240529.0",
    "wrangler": "^3.57.2"
  }
}

```

- src/index.ts

```ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => {
  return c.text('Hello Hono!')
})

export default app

```

- Terminal

```bash
wuche@cd MINGW64 /c/wudi/github/short-url
$ pnpm create hono my-app
.../1914eafb9ca-1394                     |   +1 +
.../1914eafb9ca-1394                     | Progress: resolved 1, reused 0, downloaded 1, added 1, done
create-hono version 0.12.0
✔ Using target directory … my-app
? Which template do you want to use? cloudflare-workers
✔ Cloning the template
? Do you want to install project dependencies? yes
? Which package manager do you want to use? pnpm
⠇ Installing project dependencies

```

```bash
wuche@cd MINGW64 /c/wudi/github/short-url/my-app
$ pnpm i
 WARN  2 deprecated subdependencies found: rollup-plugin-inject@3.0.2, sourcemap-codec@1.4.8
Packages: +83
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 109, reused 83, downloaded 0, added 83, done

dependencies:
+ hono 4.5.5

devDependencies:
+ @cloudflare/workers-types 4.20240806.0
+ wrangler 3.71.0

Done in 4.6s

```

```bash
wuche@cd MINGW64 /c/wudi/github/short-url/my-app
$ pnpm run dev

> @ dev C:\wudi\github\short-url\my-app
> wrangler dev src/index.ts


 ⛅️ wrangler 3.71.0
-------------------

⎔ Starting local server...
╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯
C:\wudi\github\short-url\my-app\node_modules\.pnpm\wrangler@3.71.0_@cloudflare+workers-types@4.20240806.0\node_modules\wrangler\wrangler-dist\cli.js:29768
            throw a;
            ^

MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (C:\wudi\github\short-url\my-app\node_modules\.pnpm\miniflare@3.20240806.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (C:\wudi\github\short-url\my-app\node_modules\.pnpm\miniflare@3.20240806.0\node_modules\miniflare\dist\src\index.js:3521:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}

Node.js v22.1.0
 ELIFECYCLE  Command failed with exit code 7.

```

**Comment by yusukebe** [comment]
Hi @WuChenDi 

This may be related to this Workers SDK issue: https://github.com/cloudflare/workers-sdk/issues/4709#issuecomment-2289638966

**Comment by WuChenDi** [comment]
@yusukebe 

Thank you for your response. I will look into the best way to handle this.
