### ISSUE TITLE
Running "deno test" on Hono API results in JSX errors

### ISSUE THREAD

**Issue by Hmoulvad** [honojs/hono#3522]
### What version of Hono are you using?

4.6.5

### What runtime/platform is your app running on?

Deno v2.0.0

### What steps can reproduce the bug?

I am trying to create a simple App with an API and App along side each other. I want to test both the API and APP with `Deno.test`.

This is my App
```ts
import apiRoutes from "api/routes.ts";
import appRoutes from "app/routes.tsx";
import { Hono } from "hono";

const app = new Hono();

app.route("/", appRoutes).route("/api", apiRoutes);

export default app;

```

These are my App Routes
```ts
import { Hono } from "hono";
import { jsxRenderer } from "hono/jsx-renderer";
import RootLayout from "./layout.tsx";
import HomePage from "./page.tsx";
import UIPage from "./ui/page.tsx";
import FormPage from "./form/page.tsx";

const appRoutes = new Hono();

appRoutes
  // Middleware to add the RootLayout to all routes
  .use(
    "*",
    jsxRenderer(({ children, ...rest }) => (
      <RootLayout {...rest}>{children}</RootLayout>
    ))
  )
  // Routes
  .get("/", (c) =>
    c.render(<HomePage />, {
      title: "Home Page",
      description: "This is the home page",
      path: "/",
    })
  )
  .get("/ui", (c) =>
    c.render(<UIPage />, {
      title: "UI Page",
      description: "This is the UI page",
      path: "/ui",
    })
  )
  .get("/form", (c) =>
    c.render(<FormPage />, {
      title: "Form Page",
      description: "This is the Form page",
      path: "/form",
    })
  );

export default appRoutes;
```
These are my API Routes
```ts
import { Hono } from "hono";

const apiRoutes = new Hono();

apiRoutes.get("/", (c) => {
  return c.html("Hello, World!");
});

export default apiRoutes;
```
These are the tests I try to run
```ts
import { assertEquals } from "std/assert";
import app from "../app.ts";

Deno.test("GET / should return 200", async () => {
  const res = await app.request("http://localhost/api");
  assertEquals(res.status, 200);
});
```

### What is the expected behavior?

I expect Deno to run the tests and give me back the results.

### What do you see instead?

When I run "deno test" I am getting the following error: 
```
error: TS2339 [ERROR]: Property 'title' does not exist on type 'PropsWithChildren<{ Layout: FC; }>'.
    jsxRenderer(({ children, title, description, path }) => {
                             ~~~~~
    at file:///Users/HBM/Projects/Heno/app/routes.tsx:14:30

TS2339 [ERROR]: Property 'description' does not exist on type 'PropsWithChildren<{ Layout: FC; }>'.
    jsxRenderer(({ children, title, description, path }) => {
                                    ~~~~~~~~~~~
    at file:///Users/HBM/Projects/Heno/app/routes.tsx:14:37

TS2339 [ERROR]: Property 'path' does not exist on type 'PropsWithChildren<{ Layout: FC; }>'.
    jsxRenderer(({ children, title, description, path }) => {
                                                 ~~~~
    at file:///Users/HBM/Projects/Heno/app/routes.tsx:14:50

TS2554 [ERROR]: Expected 1 arguments, but got 2.
    c.render(<HomePage />, {
                           ^
    at file:///Users/HBM/Projects/Heno/app/routes.tsx:20:28

TS2554 [ERROR]: Expected 1 arguments, but got 2.
    c.render(<UIPage />, {
                         ^
    at file:///Users/HBM/Projects/Heno/app/routes.tsx:27:26

TS2554 [ERROR]: Expected 1 arguments, but got 2.
    c.render(<FormPage />, {
                           ^
    at file:///Users/HBM/Projects/Heno/app/routes.tsx:34:28

Found 6 errors.
```

### Additional information

Github repo to reproduce: https://github.com/Hmoulvad/Heno

**Comment by yusukebe** [comment]
Hi @Hmoulvad 

Add the following definition:

```ts
declare module 'hono' {
  interface ContextRenderer {
    (content: string | Promise<string>, props: { title: string; description: string; path: string }): Response
  }
}
```

Ref: https://hono.dev/docs/middleware/builtin/jsx-renderer

**Comment by Hmoulvad** [comment]
Hi @yusukebe If you look at this file: https://github.com/Hmoulvad/Heno/blob/main/global.d.ts you can see that I've already added it. And it works fine when I run the server.

These issue only presents itself when trying to run "deno test"

**Comment by yusukebe** [comment]
@Hmoulvad 

Thank you for the explanation! I've added the definition to `app/routes.tsx` and it works well.

![CleanShot 2024-10-16 at 18 36 29@2x](https://github.com/user-attachments/assets/16b1eab4-6ffe-4cdd-81d8-06d72985ad26)

I think the `deno test` can't refer to it.

**Comment by Hmoulvad** [comment]
@yusukebe can you help me clarify what you mean by adding it to `app/routes.tsx` I can see that your tests works now.

**Comment by yusukebe** [comment]
@Hmoulvad 

Sorry for my bad explanation. I've added the declaration here:

![CleanShot 2024-10-16 at 20 36 46@2x](https://github.com/user-attachments/assets/2a20c0c1-a86d-48b6-8a10-37616dc4d168)

**Comment by Hmoulvad** [comment]
Crazy that it resolves it. It must be a "deno test" issue that it doesn't read global.d.ts

**Comment by yusukebe** [comment]
@Hmoulvad Exactly. I also think a Deno mater.

**Comment by yusukebe** [comment]
I think we can close this issue since it is a Deno-side matter.

**Comment by Hmoulvad** [comment]
I agree I should open up a ticket at Deno. Thanks for the help @yusukebe
