### ISSUE TITLE
devcontainer build error on codespaces

### ISSUE THREAD

**Issue by EdamAme-x** [honojs/hono#3581]
log

```llvm
[92184 ms] Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1730178235355/Dockerfile-with-features -t vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/hono/.devcontainer
[93033 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=******** -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
docker: --userns: invalid USER mode.
See 'docker run --help'.
[30 ms] Stop: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=******** -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
{"outcome":"error","message":"Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started\ntrap \"exit 0\" 15\n\nexec \"$@\"\nwhile sleep 1 & wait $!; do :; done -","description":"An error occurred setting up the container."}
trap "exit 0" 15
exec "$@"
while sleep 1 & wait $!; do :; done -
    at wtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1260)
    at NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1002)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
    at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
    at async prA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:663:200)
    at async drA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:662:14706)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
                                                          trap "exit 0" 15

                                                                          exec "$@"
                                                                                   while sleep 1 & wait $!; do :; done -
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.

Creating recovery container.
```

**Comment by EdamAme-x** [comment]
I think that this is side-effect of https://github.com/honojs/hono/commit/f8664b03a66b8e3abf488be0117885137904559b

**Comment by EdamAme-x** [comment]
In Japanese article
https://rheb.hatenablog.com/entry/podman3-rootless-docker-compose

says "docker doesn't support `--userns=keep-id`"

**Comment by EdamAme-x** [comment]
same issue on reddit
https://www.reddit.com/r/podman/comments/1c7civa/how_do_i_set_userns_keepid_using_podmandocker_and/
