### ISSUE TITLE
Stack traces do not use correct source code line numbers.

### ISSUE THREAD

**Issue by fresheneesz** [honojs/hono#739]
Any stack trace seems to have line numbers based on some generated bundle (index.js) instead of the line numbers from the actual source code.

For example, if I throw an error like this on line 23 of `index.ts`:
```
app.all("/", (c) => {
  throw new Error("whatever");
});
```

I get the following trace

```
Trace: Error: whatever
    at index.js:4090:9
    at Hono.dispatch (index.js:2801:15)
    at Hono.fetch (index.js:2702:19) {
  stack: Error: whatever
    at index.js:4090:9
    at Hono….js:2801:15)
    at Hono.fetch (index.js:2702:19),
  message: whatever
}
    at logConsoleMessage (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:143164:25)
    at WebSocket2.<anonymous> (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:142938:13)
    at WebSocket2.onMessage (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:121339:22)
    at WebSocket2.emit (node:events:525:35)
    at Receiver2.receiverOnMessage (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:122227:24)
    at Receiver2.emit (node:events:513:28)
    at Receiver2.dataMessage (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:120891:18)
    at Receiver2.getData (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:120833:21)
    at Receiver2.startLoop (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:120610:27)
    at Receiver2._write (/<redacted>/node_modules/wrangler/wrangler-dist/cli.js:120567:14)
```

Note that the file in the trace is `index.js` while the source code file is `index.ts`. This isn't just a typescript->javascript problem tho. If the error instead happens in some other file `like whatever.ts`, the stack trace will still have some large line number inside `index.js`. It seems index.js is some large bundle that these line numbers are coming from. This makes it very difficult to debug errors.

Also note that this isn't a cloudflare bug. Doing an equivalent thing without hono gives me proper source code files and line numbers. What is hono doing that would mutate the stack traces in this way?

**Comment by yusukebe** [comment]
Hi @fresheneesz !

Thank you for creating the issue.
I'll investigate it later (If anyone knows of a way to solve this, please let us know).

**Comment by fresheneesz** [comment]
Hmm, revisiting this, I think I may have been wrong that this is a hono issue. I am seeing the index.js and incorrect line number (albeit much smaller, that I assumed it was correct) in raw cloudflare. I'll open a cloudflare ticket.
