### ISSUE TITLE
Deno "hello world" example gives a error

### ISSUE THREAD

**Issue by tdwesten** [honojs/hono#744]
Hi there, 

I'am trying the deno Hello world [example](https://honojs.dev/docs/getting-started/deno/). But I get this typing error: 
```
Check file:///Users/thomasvanderwesten/server/thermos-api-deno/hello.ts
error: TS2345 [ERROR]: Argument of type '{ prefix: string; }' is not assignable to parameter of type 'Partial<Pick<Hono<Environment, string, unknown>, "router" | "strict">>'.
  Object literal may only specify known properties, and 'prefix' does not exist in type 'Partial<Pick<Hono<Environment, string, unknown>, "router" | "strict">>'.
const app = new Hono({ prefix: "/api/v1" });
                       ~~~~~~~~~~~~~~~~~
    at file:///Users/thomasvanderwesten/server/thermos-api-deno/hello.ts:4:24

TS2345 [ERROR]: Argument of type '(request: Request, Environment?: Bindings | undefined, executionCtx?: ExecutionContext | undefined) => Response | Promise<Response>' is not assignable to parameter of type 'string | HTTPOptions'.
serve(app.fetch);
      ~~~~~~~~~
    at file:///Users/thomasvanderwesten/server/thermos-api-deno/hello.ts:8:7

Found 2 errors.
```
When running this example:
```
import { serve } from 'https://deno.land/std/http/server.ts'
import { Hono } from 'https://deno.land/x/hono/mod.ts'

const app = new Hono()

app.get('/', (c) => c.text('Hello! Hono!'))

serve(app.fetch)
```
Deno Version;
```
deno --version
deno 1.22.0 (release, x86_64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2
```
I'am missing something.. but what?

**Comment by tdwesten** [comment]
Ok, after updating Deno to version 1.29.1 the error changed to; 
```
error: Uncaught TypeError: Error parsing args at position 0: missing field `port`
  const listener = Deno.listen(addr);
                        ^
    at Object.listen (deno:ext/net/01_net.js:302:33)
    at serve (https://deno.land/std@0.83.0/http/server.ts:306:25)
    at file:///Users/thomasvanderwesten/server/thermos-api-deno/hello.ts:8:1
```
And in VSCODE the there is still a type error;
```
Argument of type '(request: Request, Environment?: Bindings | undefined, executionCtx?: ExecutionContext | undefined) => Response | Promise<Response>' is not assignable to parameter of type 'string | HTTPOptions'.deno-ts(2345)
```

**Comment by yusukebe** [comment]
Hi @tdwesten 

It is not reproduced in my environment. How about specifying the version of modules?

```ts
import { serve } from 'https://deno.land/std@0.167.0/http/server.ts'
import { Hono } from 'https://deno.land/x/hono@v2.6.2/mod.ts'

const app = new Hono()

app.get('/', (c) => c.text('Hello! Hono!'))

serve(app.fetch)
```

**Comment by tdwesten** [comment]
Oke thanks, the problem is the "http/server.ts" package, very version from 0.167.0 up give this error. Is see there were breaking changes maybe is het breaking the demo; https://github.com/denoland/deno_std/releases/tag/0.168.0

**Comment by yusukebe** [comment]
No. With recent versions such `0.168.0` or `0.1700.0` it does not throw errors.

> at serve (https://deno.land/std@0.83.0/http/server.ts:306:25)

In this case, you are using the old version `0.83.0` so, it threw errors.

**Comment by tdwesten** [comment]
Yes now it works! Thanks!
