### ISSUE TITLE
Middleware poweredBy() causes error when using DurableObject

### ISSUE THREAD

**Issue by muslax** [honojs/hono#820]
It happened to me with this simple code:

```javascript
const app = new Hono<{ Bindings: Env }>()

app.use('*', poweredBy())

app.get('/', (c) => {
  return c.text('Hello Hono!')
})

app.get('/test', async (c) => {
  const id = c.env.AUTH.idFromName(c.env.DURABLE_AUTH_NAME)
  const stub = c.env.AUTH.get(id)
  return await stub.fetch(c.req)
})

export default app
```

When I run `yarn dev --local` and then access `/test` in browser, the console explodes with this error:
```
Trace: TypeError: immutable
    at Headers.append (/Users/polt/aces-workers/auth/node_modules/undici/lib/fetch/headers.js:227:13)
    at /Users/polt/aces-workers/auth/node_modules/hono/dist/middleware/powered-by/index.js:5:19
    at /Users/polt/aces-workers/auth/node_modules/hono/dist/hono.js:163:50
    at EventTarget.[kDispatchFetch] (/Users/polt/aces-workers/auth/node_modules/@miniflare/core/src/standards/event.ts:385:13)
    at Server.<anonymous> (/Users/polt/aces-workers/auth/node_modules/@miniflare/http-server/src/index.ts:298:20)
    at Hono.errorHandler (/Users/polt/aces-workers/auth/node_modules/hono/dist/hono.js:29:15)
    at /Users/polt/aces-workers/auth/node_modules/hono/dist/compose.js:52:27
    at /Users/polt/aces-workers/auth/node_modules/hono/dist/hono.js:163:50
    at EventTarget.[kDispatchFetch] (/Users/polt/aces-workers/auth/node_modules/@miniflare/core/src/standards/event.ts:385:
⎔ Shutting down local server.
```

The error goes away when I disable the middleware.

I am using `hono-minimal` template with Hono upgraded to version 2.7.2.

**Comment by muslax** [comment]
Update: Running `yarn dev` (without `--local` flag) produce this error:
```
Trace: TypeError: Can't modify immutable headers.
    at index.js:1238:19
    at async index.js:1213:50 {
  stack: TypeError: Can't modify immutable headers.
    at index.js:1238:19
    at async index.js:1213:50,
  message: Can't modify immutable headers.
}
    at logConsoleMessage (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:122442:25)
    at WebSocket2.<anonymous> (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:122216:13)
    at WebSocket2.onMessage (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:96544:22)
    at WebSocket2.emit (node:events:402:35)
    at Receiver2.receiverOnMessage (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:97432:24)
    at Receiver2.emit (node:events:390:28)
    at Receiver2.dataMessage (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:96096:18)
    at Receiver2.getData (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:96038:21)
    at Receiver2.startLoop (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:95815:26)
    at Receiver2._write (/Users/polt/aces-workers/auth/node_modules/wrangler/wrangler-dist/cli.js:95772:14)
```

**Comment by yusukebe** [comment]
Hi @muslax !

This is because `resp` is `Reponse` fetched from the external place.  The same error occurs in the following code as proof of this.

```ts
app.get('/', async (c) => {
  const res = await fetch('https://honojs.dev')
  res.headers.append('foo', 'bar')
  return res
})
```

To avoid it, we should `clone` it.

```ts
let res = await fetch('https://honojs.dev')
res = res.clone()
```

In practical terms, this only happens when Durable Objects or return fetched Responses directly. Therefore, we do not change powerd-by middleware to deal with this problem right now. So, please use `clone` in this case.

**Comment by akaboshinit** [comment]
I hit a similar problem with etag middleware and cloudflare cache, but I solved it, so I'll leave you with some advice.

```
app.use("*", etag());

app.get("*", async (c) => {
  const req = c.req;

  const url = new URL(req.url);
  const cacheKey = new Request(
    url.toString(),
    req
  );
  const cache = caches.default;
  const cacheImage = await cache.match(cacheKey);
  if (cacheImage) {
    console.log(`Cache hit for: ${req.url}.`);
    //   ↓ Clone the cacheImage responce before returning it!!
    return cacheImage.clone();
  }

  console.log(
    `Cache none : generate for: ${req.url}.`
  );

  const response = await fetch(
    URL
  );

  const cacheResponse = new Response(
    response.body,
    {
      headers: {
        "Cache-Control": "public, max-age=100",
        "Content-Type":
          response.headers.get("Content-Type") ??
          "image/png",
      },
    }
  );

  c.executionCtx.waitUntil(
    cache.put(cacheKey, cacheResponse.clone())
  );

  return cacheResponse;
});
```

If you do not clone the cache when returning it, the next request will have a response rewrite error as shown in the issue, so be sure to clone the cache before returning it for safe handling.

**Comment by mglikesbikes** [comment]
Seeing this issue pop up when using `cors()` and trying to deal with the `Upgrade` header needed for durable objects + websockets. `TypeError: Can't modify immutable headers.` crashes the whole worker, and I'm not in a situation where `clone()`ing it would be the issue:

```stub.fetch(c.req.url, {
headers: {
upgrade: c.header('upgrade')
}});```

anyway, turning off the cors middleware fixes everything so, FYI :)
